Repository spring-projects/spring-framework, pull requests merged in 2019-09, with the labels that each got.

#23555 Fix typos related to indefinite articles
  spring-beans/src/test/java/org/springframework/beans/AbstractPropertyAccessorTests.java
  spring-web/src/main/java/org/springframework/http/StreamingHttpOutputMessage.java
  spring-web/src/main/java/org/springframework/remoting/httpinvoker/HttpComponentsHttpInvokerRequestExecutor.java
  spring-webflux/src/main/java/org/springframework/web/reactive/function/server/RequestPredicates.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/HandlerInterceptor.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/function/RequestPredicates.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/support/DefaultHandlerExceptionResolver.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/support/ServletUriComponentsBuilder.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/RedirectView.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/ResourceBundleViewResolver.java
  src/docs/asciidoc/languages/kotlin.adoc
Labels: type: documentation

#23521 Use dependency management in Framework build
  build.gradle
  integration-tests/integration-tests.gradle
  spring-aop/spring-aop.gradle
  spring-aspects/spring-aspects.gradle
  spring-beans/spring-beans.gradle
  spring-context-indexer/spring-context-indexer.gradle
  spring-context-support/spring-context-support.gradle
  spring-context/spring-context.gradle
  spring-core/spring-core.gradle
  spring-jcl/spring-jcl.gradle
  spring-jdbc/spring-jdbc.gradle
  spring-jms/spring-jms.gradle
  spring-messaging/spring-messaging.gradle
  spring-orm/spring-orm.gradle
  spring-oxm/spring-oxm.gradle
  spring-test/spring-test.gradle
  spring-tx/spring-tx.gradle
  spring-web/spring-web.gradle
  spring-webflux/spring-webflux.gradle
  spring-webmvc/spring-webmvc.gradle
  spring-websocket/spring-websocket.gradle
Labels: type: enhancement

#23591 Add opt-in build scan integration with Gradle Enterprise
  build.gradle
  gradle.properties
  gradle/build-scan-user-data.gradle
Labels: type: task

#23597 Tweak detection of Bamboo
  gradle/build-scan-user-data.gradle
Labels: type: task

#23603 Fix typo
  spring-jdbc/src/main/java/org/springframework/jdbc/SQLWarningException.java
  spring-jdbc/src/main/java/org/springframework/jdbc/UncategorizedSQLException.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/BatchPreparedStatementSetter.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/CallableStatementCallback.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/CallableStatementCreatorFactory.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/ConnectionCallback.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/DisposableSqlTypeValue.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcOperations.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/ParameterDisposer.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/ParameterMapper.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/ParameterizedPreparedStatementSetter.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCreatorFactory.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementSetter.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/ResultSetExtractor.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/RowCallbackHandler.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/SqlParameter.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/SqlParameterValue.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/SqlReturnType.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/SqlTypeValue.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/StatementCallback.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/StatementCreatorUtils.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/metadata/CallMetaDataContext.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/AbstractSqlParameterSource.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/NamedParameterJdbcOperations.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/NamedParameterUtils.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/support/AbstractInterruptibleBatchPreparedStatementSetter.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/support/AbstractSqlTypeValue.java
  spring-jdbc/src/main/java/org/springframework/jdbc/datasource/SingleConnectionDataSource.java
  spring-jdbc/src/main/java/org/springframework/jdbc/object/SqlCall.java
  spring-jdbc/src/main/java/org/springframework/jdbc/object/SqlOperation.java
  spring-jdbc/src/main/java/org/springframework/jdbc/object/SqlQuery.java
  spring-jdbc/src/main/java/org/springframework/jdbc/object/SqlUpdate.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/DatabaseMetaDataCallback.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/JdbcAccessor.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/SQLErrorCodeSQLExceptionTranslator.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/SqlValue.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/rowset/SqlRowSet.java
  spring-tx/src/main/java/org/springframework/dao/UncategorizedDataAccessException.java
Labels: type: documentation

#23619 Upgrade to com.gradle.build-scan 2.4.2
  build.gradle
Labels: type: task

#23643 Remove unused test assert in RowMapperTests
  spring-jdbc/src/test/java/org/springframework/jdbc/core/RowMapperTests.java
Labels: type: task

#23642 Fix race condition in sendBlockingMessage
  spring-websocket/src/test/java/org/springframework/web/socket/handler/ConcurrentWebSocketSessionDecoratorTests.java
Labels: type: task

#23645 Allow registration of RSocket metadata extractors
  spring-messaging/src/main/java/org/springframework/messaging/rsocket/DefaultMetadataExtractor.java
  spring-messaging/src/main/java/org/springframework/messaging/rsocket/DefaultRSocketStrategies.java
  spring-messaging/src/main/java/org/springframework/messaging/rsocket/MetadataExtractor.java
  spring-messaging/src/main/java/org/springframework/messaging/rsocket/MetadataExtractorRegistry.java
  spring-messaging/src/main/java/org/springframework/messaging/rsocket/RSocketStrategies.java
  spring-messaging/src/test/java/org/springframework/messaging/rsocket/DefaultRSocketStrategiesTests.java
Labels: type: enhancement

#23562 Omit cancellation of transactional Monos in TransactionOperator
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionalOperator.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionalOperatorImpl.java
  spring-tx/src/test/java/org/springframework/transaction/reactive/TransactionalOperatorTests.java
Labels: in: data, type: enhancement

#23690 Obfuscate IP addresses in build scans
  build.gradle
Labels: type: task

#23691 Capture maxParallelForks of Test tasks in build scans
  gradle/build-scan-user-data.gradle
Labels: type: task

#23701 Run webflux's tests in parallel to shorten long tail of builds
  spring-webflux/spring-webflux.gradle
Labels: type: task

#23702 Improve exclusions of checkstyleNoHttp task
  build.gradle
Labels: type: task

#23703 Upgrade to io.freefair.aspectj 4.1.1
  build.gradle
Labels: type: task

#23704 Allow genJaxb's output to be cached when checkout locations differ
  spring-oxm/spring-oxm.gradle
Labels: type: task

#23719 Fix an assertion in a test
  spring-context/src/test/java/org/springframework/context/annotation/AnnotationConfigApplicationContextTests.java
Labels: type: task

#23726 Fix typo in DispatcherServlet Javadoc
  spring-webmvc/src/main/java/org/springframework/web/servlet/DispatcherServlet.java
Labels: type: documentation
