Repository spring-projects/spring-framework, pull requests merged in 2019-02, with the labels that each got.

#22278 Use AtomicInteger instead of unsafe increment on volatile fields
  spring-aop/src/main/java/org/springframework/aop/support/ControlFlowPointcut.java
  spring-core/src/main/java/org/springframework/util/ConcurrentReferenceHashMap.java
  spring-expression/src/main/java/org/springframework/expression/spel/standard/SpelExpression.java
Labels: type: enhancement

#22297 Load-time weaving support for WildFly 13+
  spring-context/src/main/java/org/springframework/instrument/classloading/jboss/JBossLoadTimeWeaver.java
Labels: type: enhancement

#22260 Add tests for SpringBeanContainer (Hibernate ORM integration) and fix the behavior when requesting named beans
  spring-orm/src/main/java/org/springframework/orm/hibernate5/SpringBeanContainer.java
  spring-orm/src/test/java/org/springframework/orm/jpa/hibernate/HibernateNativeEntityManagerFactorySpringBeanContainerIntegrationTests.java
  spring-orm/src/test/java/org/springframework/orm/jpa/hibernate/beans/BeanSource.java
  spring-orm/src/test/java/org/springframework/orm/jpa/hibernate/beans/MultiplePrototypesInSpringContextTestBean.java
  spring-orm/src/test/java/org/springframework/orm/jpa/hibernate/beans/NoDefinitionInSpringContextTestBean.java
  spring-orm/src/test/java/org/springframework/orm/jpa/hibernate/beans/SinglePrototypeInSpringContextTestBean.java
  spring-orm/src/test/java/org/springframework/orm/jpa/hibernate/beans/TestBean.java
  spring-orm/src/test/resources/org/springframework/orm/jpa/hibernate/inject-hibernate-spring-bean-container-tests.xml
Labels: type: bug

#22392 Fix for ScriptUtils failure when '--' occurs inside a multi-line comment on the same line as '*/'
  spring-jdbc/src/main/java/org/springframework/jdbc/datasource/init/ScriptUtils.java
  spring-jdbc/src/test/java/org/springframework/jdbc/datasource/init/ScriptUtilsUnitTests.java
  spring-jdbc/src/test/resources/org/springframework/jdbc/datasource/init/test-data-with-multi-line-nested-comments.sql
Labels: type: enhancement

#22418 Some very simple improvements regarding usage of ArrayList
  spring-context-support/src/main/java/org/springframework/cache/jcache/interceptor/AbstractJCacheOperation.java
  spring-core/src/main/java/org/springframework/util/StringUtils.java
  spring-messaging/src/main/java/org/springframework/messaging/support/MessageHeaderAccessor.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/tags/form/ErrorsTag.java
Labels: type: enhancement

#22404 Extract duplicated code into a separate method
  spring-core/src/main/java/org/springframework/util/ClassUtils.java
Labels: status: waiting-for-triage

#22387 Simplify ConcurrentReferenceHashMap
  spring-core/src/main/java/org/springframework/util/ConcurrentReferenceHashMap.java
Labels: status: waiting-for-triage

#22258 Use Method in CglibAopProxy.fixedInterceptorMap instead of String returned from Method::toString
  spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java
  spring-aop/src/main/java/org/springframework/aop/framework/ObjenesisCglibAopProxy.java
Labels: status: waiting-for-triage, type: enhancement

#22330 Use StringJoiner where possible to simplify String joining
  spring-beans/src/main/java/org/springframework/beans/propertyeditors/ClassArrayEditor.java
  spring-core/src/main/java/org/springframework/util/StringUtils.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/CompoundExpression.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/FormatHelper.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/FunctionReference.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/Indexer.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/MethodReference.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/metadata/TableMetaDataContext.java
Labels: type: enhancement

#22430 Use StringJoiner where possible to simplify String joining
  spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassParser.java
  spring-core/src/main/java/org/springframework/util/ClassUtils.java
  spring-web/src/main/java/org/springframework/http/HttpHeaders.java
Labels: type: enhancement

#22466 Simplify String concatenation
  spring-test/src/main/java/org/springframework/mock/web/MockHttpServletResponse.java
Labels: status: waiting-for-triage

#22443 Polish
  spring-messaging/src/main/java/org/springframework/messaging/simp/stomp/StompSession.java
  spring-web/src/main/java/org/springframework/http/HttpHeaders.java
  spring-web/src/main/java/org/springframework/web/server/adapter/HttpWebHandlerAdapter.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/method/AbstractHandlerMethodMapping.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/handler/AbstractHandlerMethodMapping.java
Labels: type: task

#22469 Instantiate ArrayList class with a exact initial capacity
  spring-context/src/main/java/org/springframework/context/support/PostProcessorRegistrationDelegate.java
Labels: type: task

#2060 Open parameter autowiring utility for external use
  spring-beans/src/main/java/org/springframework/beans/factory/support/AutowireUtils.java
  spring-beans/src/test/java/org/springframework/beans/factory/support/AutowireUtilsTests.java
  spring-test/src/main/java/org/springframework/test/context/junit/jupiter/ParameterAutowireUtils.java
  spring-test/src/main/java/org/springframework/test/context/junit/jupiter/SpringExtension.java
Labels: in: core, in: test, type: enhancement
