Repository spring-projects/spring-framework, pull requests merged in 2019-11, with the labels that each got.

#23916 Polish
  spring-webflux/src/main/java/org/springframework/web/reactive/function/client/WebClientUtils.java
Labels: status: waiting-for-triage

#23949 Use Method::getParameterCount where possible
  spring-aop/src/main/java/org/springframework/aop/framework/AopProxyUtils.java
  spring-beans/src/main/java/org/springframework/beans/ExtendedBeanInfo.java
  spring-beans/src/main/java/org/springframework/beans/PropertyDescriptorUtils.java
  spring-beans/src/main/java/org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/ConstructorResolver.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/DisposableBeanAdapter.java
  spring-context/src/main/java/org/springframework/jmx/export/assembler/InterfaceBasedMBeanInfoAssembler.java
  spring-core/src/main/java/org/springframework/core/BridgeMethodResolver.java
  spring-core/src/main/java/org/springframework/util/MethodInvoker.java
  spring-core/src/main/java/org/springframework/util/ReflectionUtils.java
  spring-expression/src/main/java/org/springframework/expression/spel/support/ReflectiveConstructorExecutor.java
  spring-expression/src/main/java/org/springframework/expression/spel/support/ReflectiveConstructorResolver.java
  spring-expression/src/main/java/org/springframework/expression/spel/support/ReflectiveMethodExecutor.java
  spring-expression/src/main/java/org/springframework/expression/spel/support/ReflectiveMethodResolver.java
Labels: in: core, type: enhancement

#23955 Delete unnecessary variable assignment
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanFactory.java
Labels: in: core, type: task

#23971 Upgrade to Shadow Plugin 5.2.0
  spring-core/spring-core.gradle
Labels: type: task

#23970 Tidy up classpath pollution caused by resource creation in the tests
  spring-webflux/src/test/java/org/springframework/web/reactive/resource/CachingResourceResolverTests.java
  spring-webflux/src/test/java/org/springframework/web/reactive/resource/CssLinkResourceTransformerTests.java
  spring-webflux/src/test/java/org/springframework/web/reactive/resource/EncodedResourceResolverTests.java
  spring-webflux/src/test/java/org/springframework/web/reactive/resource/GzipSupport.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/resource/CachingResourceResolverTests.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/resource/CssLinkResourceTransformerTests.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/resource/EncodedResourceResolverTests.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/resource/GzipSupport.java
  src/checkstyle/checkstyle-suppressions.xml
Labels: type: task

#23969 Simplify ConstructorResolver: do not sort intermediate array
  spring-beans/src/main/java/org/springframework/beans/factory/support/AutowireUtils.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/ConstructorResolver.java
Labels: in: core, type: enhancement

#23965 Avoid store all beanName in ApplicationListenerDetector
  spring-context/src/main/java/org/springframework/context/support/ApplicationListenerDetector.java
Labels: in: core, type: enhancement

#23784 ApplicationListenerMethodAdapter: gracefully handle beans which are actually NullBean
  spring-context/src/main/java/org/springframework/context/event/ApplicationListenerMethodAdapter.java
  spring-context/src/test/java/org/springframework/context/event/AnnotationDrivenEventListenerTests.java
Labels: in: core, type: enhancement

#23981 Polish AbstractAutowireCapableBeanFactory#populateBean
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractAutowireCapableBeanFactory.java
Labels: in: core, type: task

#23986 Use array.clone() instead of manual array creation
  spring-aop/src/main/java/org/springframework/aop/framework/ReflectiveMethodInvocation.java
  spring-context-support/src/main/java/org/springframework/mail/SimpleMailMessage.java
  spring-context/src/main/java/org/springframework/cache/interceptor/SimpleKey.java
  spring-core/src/main/java/org/springframework/util/FastByteArrayOutputStream.java
Labels: status: waiting-for-triage

#23814 AbstractRequestLoggingFilter.isIncludeHeaders() declared as protected
  spring-web/src/main/java/org/springframework/web/filter/AbstractRequestLoggingFilter.java
Labels: in: web, type: bug

#23992 Fix inappropriate eager init.
  spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultListableBeanFactory.java
Labels: status: waiting-for-triage

#24008 Fix errors in documentation
  src/docs/asciidoc/rsocket.adoc
  src/docs/asciidoc/web/webflux-functional.adoc
  src/docs/asciidoc/web/webflux.adoc
  src/docs/asciidoc/web/webmvc-functional.adoc
  src/docs/asciidoc/web/webmvc.adoc
Labels: type: documentation

#24048 Polish AbstractBeanDefinition
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanDefinition.java
Labels: in: core, type: task

#24052 Use String.isEmpty() instead of String.equals("")
  spring-beans/src/main/java/org/springframework/beans/factory/annotation/AnnotationBeanWiringInfoResolver.java
  spring-test/src/main/java/org/springframework/mock/jndi/SimpleNamingContext.java
  spring-web/src/main/java/org/springframework/http/codec/ServerSentEventHttpMessageReader.java
  spring-web/src/main/java/org/springframework/http/server/DefaultPathContainer.java
  spring-web/src/main/java/org/springframework/web/util/pattern/PathPattern.java
Labels: status: waiting-for-triage

#24072 Cache result of String.getBytes() in ExtendedBeanInfo.PropertyDescriptorComparator
  spring-beans/src/main/java/org/springframework/beans/ExtendedBeanInfo.java
Labels: in: core, type: enhancement

#24096 Remove duplicate checks in ResponseCookieTests
  spring-web/src/test/java/org/springframework/http/ResponseCookieTests.java
Labels: status: waiting-for-triage

#24105 Enable reading from the remote build cache for all
  build.gradle
  gradle/build-cache-settings.gradle
Labels: type: task
