Repository spring-projects/spring-framework, pull requests merged in 2019-03, with the labels that each got.

#22502 Use String::isEmpty instead of "".equals(arg) when arg is not null
  spring-beans/src/main/java/org/springframework/beans/propertyeditors/StringTrimmerEditor.java
  spring-context/src/main/java/org/springframework/jndi/JndiTemplateEditor.java
  spring-orm/src/main/java/org/springframework/orm/jpa/support/PersistenceAnnotationBeanPostProcessor.java
  spring-test/src/main/java/org/springframework/test/web/servlet/htmlunit/MockMvcWebConnection.java
  spring-test/src/main/java/org/springframework/test/web/servlet/setup/PatternMappingFilterProxy.java
  spring-web/src/main/java/org/springframework/web/util/WebUtils.java
Labels: type: enhancement

#22515 URL Cleanup
  build.gradle
  gradle/docs.gradle
  gradle/ide.gradle
  gradle/publish-maven.gradle
Labels: type: task

#22513 Fix javadoc for AbstractApplicationContext.registerBeanPostProcessors()
  spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java
Labels: in: core, type: documentation

#22516 URL Cleanup
  build.gradle
  gradle/publish-maven.gradle
  import-into-eclipse.bat
  import-into-eclipse.sh
Labels: type: task

#22539 Use StringJoiner where possible to simplify String joining
  spring-core/src/main/java/org/springframework/util/ObjectUtils.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/InlineList.java
  spring-web/src/main/java/org/springframework/http/HttpHeaders.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/condition/AbstractRequestCondition.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/condition/AbstractRequestCondition.java
Labels: type: task

#22542 Polish: do simple clean-up
  spring-beans/src/main/java/org/springframework/beans/factory/config/YamlProcessor.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanDefinition.java
  spring-messaging/src/main/java/org/springframework/messaging/simp/stomp/StompDecoder.java
Labels: type: task

#22545 Migrate CacheControl to use java.time.Duration for durations
  spring-web/src/main/java/org/springframework/http/CacheControl.java
  spring-web/src/test/java/org/springframework/http/CacheControlTests.java
Labels: type: enhancement

#22553 Fixed a typo in @NonNullFields (Obvious Fix)
  spring-core/src/main/java/org/springframework/lang/NonNullFields.java
Labels: type: documentation

#22517 URL Cleanup
  build.gradle
  gradle/publish-maven.gradle
  import-into-eclipse.bat
  import-into-eclipse.sh
Labels: status: waiting-for-triage

#22573 Add missing break statements to stop looping when result is known
  spring-beans/src/test/java/org/springframework/beans/ExtendedBeanInfoTests.java
  spring-context/src/main/java/org/springframework/scripting/support/StandardScriptFactory.java
  spring-core/src/test/java/org/springframework/core/io/support/PathMatchingResourcePatternResolverTests.java
Labels: status: waiting-for-triage, type: task

#22518 URL Cleanup
  build.gradle
  gradle/ide.gradle
  gradle/publish-maven.gradle
  import-into-eclipse.bat
  import-into-eclipse.sh
Labels: type: task

#22519 URL Cleanup
  build.gradle
  gradle/ide.gradle
  gradle/publish-maven.gradle
  import-into-eclipse.bat
  import-into-eclipse.sh
Labels: type: task

#22589 Fix typo
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseEntityExceptionHandler.java
Labels: type: documentation

#22593 Simplify String concatenation
  spring-beans/src/main/java/org/springframework/beans/factory/config/BeanDefinitionHolder.java
  spring-core/src/main/java/org/springframework/core/ResolvableType.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/Selection.java
  spring-test/src/main/java/org/springframework/mock/web/MockHttpServletRequest.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/condition/AbstractMediaTypeExpression.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/condition/AbstractMediaTypeExpression.java
Labels: in: core, type: task

#22595 Use Arrays::fill instead of hand-written loop
  spring-websocket/src/main/java/org/springframework/web/socket/sockjs/client/AbstractXhrTransport.java
  spring-websocket/src/main/java/org/springframework/web/socket/sockjs/transport/handler/XhrStreamingTransportHandler.java
Labels: in: web, type: task

#22621 Fix grammar issues
  src/docs/asciidoc/core/core-aop.adoc
Labels: type: documentation, type: task

#22628 Fix grammar issue
  src/docs/asciidoc/web/webmvc.adoc
Labels: type: task

#22639 Fix grammar issue
  src/docs/asciidoc/web/webmvc.adoc
Labels: type: task

#22645 Polish docs
  spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/support/AbstractNamedValueMethodArgumentResolver.java
  spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/support/reactive/AbstractNamedValueMethodArgumentResolver.java
  src/docs/asciidoc/web/webmvc.adoc
Labels: type: documentation

#22354 Use JUnit 4's built-in expected exception support in BeanUtilsTests
  spring-beans/src/test/java/org/springframework/beans/BeanUtilsTests.java
Labels: type: task

#22648 Remove redundant 'String.substring()' call
  spring-web/src/main/java/org/springframework/web/util/HtmlCharacterEntityDecoder.java
Labels: in: web, type: task

#22681 URL Cleanup
  index.html
Labels: type: task
