Repository spring-projects/spring-framework, pull requests merged in 2019-06, with the labels that each got.

#23098 Simplify comparison of primitives
  spring-expression/src/main/java/org/springframework/expression/spel/support/ReflectiveConstructorResolver.java
  spring-expression/src/main/java/org/springframework/expression/spel/support/StandardTypeComparator.java
Labels: type: task

#23068 Fix duplicate invoke method of transformedBeanName
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanFactory.java
Labels: in: core, type: task

#23102 Simplify String concatenation
  spring-aop/src/main/java/org/springframework/aop/aspectj/AspectJExpressionPointcut.java
  spring-beans/src/main/java/org/springframework/beans/AbstractNestablePropertyAccessor.java
  spring-beans/src/main/java/org/springframework/beans/MutablePropertyValues.java
  spring-beans/src/main/java/org/springframework/beans/factory/config/BeanDefinitionHolder.java
Labels: in: core, type: task

#23128 Add since for JettyClientHttpConnector change
  spring-web/src/main/java/org/springframework/http/client/reactive/JettyClientHttpConnector.java
Labels: in: web, type: documentation

#23145 Polish MappingMediaTypeFileExtensionResolver.addFileExtension()
  spring-web/src/main/java/org/springframework/web/accept/MappingMediaTypeFileExtensionResolver.java
Labels: in: core, type: task

#23180 Fix typos in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type: documentation

#23191 Remove duplicate assertion
  spring-core/src/test/java/org/springframework/core/annotation/AnnotatedElementUtilsTests.java
Labels: type: task
