Repository spring-projects/spring-framework, pull requests merged in 2019-05, with the labels that each got.

#22646 Add reactive transaction support SPI
  spring-tx/spring-tx.gradle
  spring-tx/src/main/java/org/springframework/transaction/ReactiveTransactionManager.java
  spring-tx/src/main/java/org/springframework/transaction/ReactiveTransactionStatus.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/AbstractReactiveTransactionManager.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/AbstractReactiveTransactionStatus.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/DefaultReactiveTransactionStatus.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/DefaultTransactionalOperator.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/ReactiveResourceHolderSynchronization.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/ReactiveTransactionCallback.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/ReactiveTransactionSynchronization.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/ReactiveTransactionSynchronizationManager.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/ReactiveTransactionSynchronizationUtils.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionContext.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionContextHolder.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionContextManager.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionalOperator.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/package-info.java
  spring-tx/src/test/java/org/springframework/transaction/reactive/ReactiveTestTransactionManager.java
  spring-tx/src/test/java/org/springframework/transaction/reactive/ReactiveTransactionSupportUnitTests.java
  spring-tx/src/test/java/org/springframework/transaction/reactive/TransactionalOperatorTests.java
Labels: in: data, type: enhancement

#22883 Use HttpHeaders constants where possible
  spring-web/src/main/java/org/springframework/web/context/request/ServletWebRequest.java
  spring-web/src/main/java/org/springframework/web/filter/ShallowEtagHeaderFilter.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ServletInvocableHandlerMethod.java
Labels: status: waiting-for-triage

#22900 Check if null before accessing exception message in webflux InvocableHandlerMethod#logArgumentErrorIfNecessary
  spring-webflux/src/main/java/org/springframework/web/reactive/result/method/InvocableHandlerMethod.java
Labels: in: web, type: bug

#22911 Replace signal materialization in TransactionAspectSupport with usingWhen
  spring-tx/src/main/java/org/springframework/transaction/interceptor/TransactionAspectSupport.java
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionContextManager.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/AbstractReactiveTransactionAspectTests.java
Labels: in: data, type: enhancement

#22421 LinkedMultiValueMap.getFirst - check that values is not empty
  spring-core/src/main/java/org/springframework/util/LinkedMultiValueMap.java
Labels: in: core, type: bug

#22916 Add a space in the documentation index file
  src/docs/asciidoc/index.adoc
Labels: status: waiting-for-triage

#22917 Fix typo
  spring-websocket/src/main/java/org/springframework/web/socket/messaging/SubProtocolWebSocketHandler.java
Labels: status: waiting-for-triage

#22935 Fix trivial errors in `integration.adoc`
  src/docs/asciidoc/integration.adoc
Labels: in: core, type: task

#22953 Add a missing single quote in assertion message
  spring-webmvc/src/main/java/org/springframework/web/servlet/resource/ResourceUrlEncodingFilter.java
Labels: in: web, type: task

#22956 Iteration over a map using EntrySet
  spring-messaging/src/main/java/org/springframework/messaging/handler/invocation/AbstractMethodMessageHandler.java
  spring-messaging/src/main/java/org/springframework/messaging/handler/invocation/reactive/InvocableHelper.java
  spring-oxm/src/main/java/org/springframework/oxm/jaxb/Jaxb2Marshaller.java
  spring-test/src/main/java/org/springframework/mock/web/HeaderValueHolder.java
  spring-test/src/main/java/org/springframework/test/web/servlet/request/MockHttpServletRequestBuilder.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/ControllerMethodResolver.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/WebContentInterceptor.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/support/AbstractFlashMapManager.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/tags/form/AbstractHtmlElementTag.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/tags/form/FormTag.java
Labels: status: waiting-for-triage

#22998 Fix typo
  spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/support/MessageMethodArgumentResolver.java
  spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/support/PayloadMethodArgumentResolver.java
Labels: status: waiting-for-triage

#22984 A couple of trivial simplifications
  spring-aop/src/main/java/org/springframework/aop/framework/JdkDynamicAopProxy.java
  spring-beans/src/main/java/org/springframework/beans/TypeConverterDelegate.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/Projection.java
  spring-websocket/src/main/java/org/springframework/web/socket/sockjs/support/AbstractSockJsService.java
Labels: in: core, type: task

#23006 Upgrade to asciidoctorj-pdf version 1.5.0-alpha.17
  build.gradle
Labels: type: task

#23020 Fix code example for validation on functional endpoints
  src/docs/asciidoc/web/webflux-functional.adoc
Labels: type: documentation

#23034 Tiny simplifications regarding usage of Iterator
  spring-jdbc/src/main/java/org/springframework/jdbc/object/BatchSqlUpdate.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/RedirectView.java
Labels: type: task

#23036 Allocate objects only when it's necessary
  spring-jdbc/src/main/java/org/springframework/jdbc/core/simple/AbstractJdbcInsert.java
  spring-test/src/main/java/org/springframework/test/context/support/AbstractContextLoader.java
  spring-test/src/main/java/org/springframework/test/context/support/TestPropertySourceAttributes.java
  spring-tx/src/main/java/org/springframework/transaction/support/AbstractPlatformTransactionManager.java
Labels: type: task

#23046 Fix typo
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: documentation

#23047 Tiny improvements regarding usage of ArrayList
  spring-expression/src/main/java/org/springframework/expression/spel/ast/InlineList.java
  spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/support/AnnotationExceptionHandlerMethodResolver.java
Labels: type: task

#23053 Simplify iteration over a map
  spring-jms/src/main/java/org/springframework/jms/support/SimpleJmsHeaderMapper.java
  spring-test/src/main/java/org/springframework/test/context/cache/DefaultContextCache.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/SessionAttributesHandler.java
Labels: in: core, in: test, type: task
