Repository spring-projects/spring-framework, pull requests merged in 2019-12, with the labels that each got.

#24108 [*.*] is displayed as [bold .] ,need to escape
  src/docs/asciidoc/core/core-aop.adoc
Labels: type: documentation

#24137 Fix status code in webflux.adoc
  src/docs/asciidoc/web/webflux.adoc
Labels: type: task

#24135 Add firstElement to CollectionUtils
  spring-core/src/main/java/org/springframework/util/CollectionUtils.java
Labels: in: core, type: enhancement

#24145 Support variable resolution of wildcard types
  spring-core/src/main/java/org/springframework/core/ResolvableType.java
  spring-core/src/test/java/org/springframework/core/ResolvableTypeTests.java
Labels: in: core, type: enhancement

#24153 Hoist Class.getName() from String concatenation to dodge an issue related to profile pollution
  spring-aop/src/main/java/org/springframework/aop/interceptor/SimpleTraceInterceptor.java
  spring-beans/src/main/java/org/springframework/beans/BeanUtils.java
  spring-core/src/main/java/org/springframework/util/ObjectUtils.java
  spring-web/src/main/java/org/springframework/web/server/handler/DefaultWebFilterChain.java
Labels: in: core, type: enhancement

#24155 Add missing backtick in WebSocket documentation
  src/docs/asciidoc/web/websocket.adoc
Labels: type: documentation

#24167 Hoist constant result of SerializableTypeWrapper.unwrap() out of loop
  spring-core/src/main/java/org/springframework/core/ResolvableType.java
Labels: in: core, type: enhancement

#24185 Short-circuit in AbstractBeanDefinition.equals()
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanDefinition.java
Labels: in: core, type: enhancement

#24195 Add BeanPropertyRowMapper.newInstance(mappedClass, conversionService)
  spring-jdbc/src/main/java/org/springframework/jdbc/core/BeanPropertyRowMapper.java
Labels: in: data, type: enhancement

#24200 MappingJackson2MessageConverter: fix javadoc typo
  spring-jms/src/main/java/org/springframework/jms/support/converter/MappingJackson2MessageConverter.java
Labels: in: messaging, type: documentation

#24205 Simplify AdvisedSupport.removeAdvisor()
  spring-aop/src/main/java/org/springframework/aop/framework/AdvisedSupport.java
Labels: in: core, type: enhancement

#24245 Fix example in RSocket docs
  src/docs/asciidoc/rsocket.adoc
Labels: type: documentation

#24276 [spring expression doc] symbolic logical operators
  src/docs/asciidoc/core/core-expressions.adoc
Labels: type: documentation
