Repository spring-projects/spring-framework, pull requests merged in 2019-08, with the labels that each got.

#23345 Introduce interface cache for proxied EntityManager and Query types
  spring-orm/src/main/java/org/springframework/orm/jpa/ExtendedEntityManagerCreator.java
  spring-orm/src/main/java/org/springframework/orm/jpa/SharedEntityManagerCreator.java
Labels: in: data, type: enhancement

#23401 Fix grammar in package-info.java
  spring-context/src/main/java/org/springframework/ejb/access/package-info.java
Labels: type: documentation

#23439 Fix */* in Javadoc
  spring-web/src/main/java/org/springframework/http/converter/ByteArrayHttpMessageConverter.java
  spring-web/src/main/java/org/springframework/http/converter/StringHttpMessageConverter.java
Labels: type: documentation

#23445 Simplify the if statements and replace 'try finally' with 'try' with resources
  spring-core/src/main/java/org/springframework/util/xml/AbstractStaxXMLReader.java
  spring-jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceTransactionManager.java
Labels: type: task

#23450 Fix data access documentation typo
  src/docs/asciidoc/data-access.adoc
Labels: type: documentation

#23457 Modify the javadoc of @EnableWebFlux annotation
  spring-webflux/src/main/java/org/springframework/web/reactive/config/EnableWebFlux.java
Labels: in: web, type: documentation

#23477 Remove unnecessary semicolon
  spring-core/src/main/java/org/springframework/core/annotation/AnnotatedElementUtils.java
Labels: type: task

#23487 Fix unmatched parenthesis in the documentation of ContextHierarchy
  spring-test/src/main/java/org/springframework/test/context/ContextHierarchy.java
Labels: in: test, type: documentation

#23519 Add @since for getCacheFilter and setCacheFilter
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/AbstractCachingViewResolver.java
Labels: type: documentation

#23458 Use lambda expressions instead of anonymous classes in spring-aop tests
  spring-aop/src/test/java/org/springframework/aop/aspectj/MethodInvocationProceedingJoinPointTests.java
  spring-aop/src/test/java/org/springframework/aop/aspectj/annotation/AbstractAspectJAdvisorFactoryTests.java
  spring-aop/src/test/java/org/springframework/aop/aspectj/autoproxy/AspectJPrecedenceComparatorTests.java
  spring-aop/src/test/java/org/springframework/aop/framework/MethodInvocationTests.java
  spring-aop/src/test/java/org/springframework/aop/framework/NullPrimitiveTests.java
  spring-aop/src/test/java/org/springframework/aop/framework/ProxyFactoryTests.java
  spring-aop/src/test/java/org/springframework/aop/support/PointcutsTests.java
  spring-webflux/src/main/java/org/springframework/web/reactive/config/ViewResolverRegistry.java
Labels: in: core, type: task

#23470 Simplify String concatenation
  spring-core/src/main/java/org/springframework/util/backoff/FixedBackOff.java
  spring-web/src/main/java/org/springframework/web/util/HierarchicalUriComponents.java
  spring-webflux/src/main/java/org/springframework/web/reactive/resource/CachingResourceResolver.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/resource/CachingResourceResolver.java
Labels: type: task

#23478 Use Collections.addAll where feasible
  spring-core/src/main/java/org/springframework/core/env/AbstractEnvironment.java
  spring-core/src/main/java/org/springframework/core/env/AbstractPropertyResolver.java
Labels: status: waiting-for-feedback, type: task
