Repository spring-projects/spring-framework, pull requests merged in 2019-04, with the labels that each got.

#22711 Primary resolution against FactoryBean instances
  spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultListableBeanFactory.java
  spring-beans/src/test/java/org/springframework/beans/factory/DefaultListableBeanFactoryTests.java
Labels: in: core, type: enhancement

#21855 Correctly parse property name in path "map[key[foo]]"
  spring-beans/src/main/java/org/springframework/beans/AbstractNestablePropertyAccessor.java
  spring-beans/src/test/java/org/springframework/beans/AbstractPropertyAccessorTests.java
  spring-beans/src/test/java/org/springframework/tests/sample/beans/IndexedTestBean.java
Labels: in: core, type: enhancement

#22728 Release cached item in ChannelSendOperator when server error
  spring-web/src/main/java/org/springframework/http/server/reactive/ChannelSendOperator.java
Labels: status: waiting-for-triage

#22596 Avoid calling other bean methods in web config
  spring-test/src/main/java/org/springframework/test/web/servlet/setup/StandaloneMockMvcBuilder.java
  spring-webflux/src/main/java/org/springframework/web/reactive/config/DelegatingWebFluxConfiguration.java
  spring-webflux/src/main/java/org/springframework/web/reactive/config/WebFluxConfigurationSupport.java
  spring-webflux/src/test/java/org/springframework/web/reactive/config/DelegatingWebFluxConfigurationTests.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/DelegatingWebMvcConfiguration.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/config/annotation/DelegatingWebMvcConfigurationTests.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupportExtensionTests.java
Labels: in: web, type: enhancement

#22737 Use StringJoiner where possible to simplify String joining
  spring-context/src/main/java/org/springframework/validation/DefaultMessageCodesResolver.java
  spring-core/src/main/java/org/springframework/core/convert/support/CollectionToStringConverter.java
  spring-messaging/src/main/java/org/springframework/messaging/handler/AbstractMessageCondition.java
  spring-web/src/main/java/org/springframework/http/HttpRange.java
  spring-web/src/main/java/org/springframework/web/util/HierarchicalUriComponents.java
Labels: status: waiting-for-triage

#22755 Fix broken asciidoc heading
  src/docs/asciidoc/core/core-null-safety.adoc
Labels: type: task

#22768 Small typo in JavaDoc for UrlPathHelper.setUrlDecode() method
  spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java
Labels: type: documentation

#22773 Use concatenation instead of torn StringBuilder::append chain
  spring-aop/src/main/java/org/springframework/aop/interceptor/AbstractMonitoringInterceptor.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/GenericBeanDefinition.java
  spring-context-support/src/main/java/org/springframework/cache/jcache/interceptor/AnnotationJCacheOperationSource.java
Labels: status: waiting-for-triage

#22777 Update Scheduled.java Javadoc to explicitly include cron element order
  spring-context/src/main/java/org/springframework/scheduling/annotation/Scheduled.java
Labels: type: documentation

#22804 Make inner classes static where possible
  spring-aop/src/main/java/org/springframework/aop/aspectj/annotation/InstantiationModelAwarePointcutAdvisorImpl.java
  spring-context/src/main/java/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor.java
  spring-core/src/main/java/org/springframework/core/convert/support/IntegerToEnumConverterFactory.java
  spring-core/src/main/java/org/springframework/core/convert/support/StringToEnumConverterFactory.java
  spring-tx/src/main/java/org/springframework/transaction/interceptor/TransactionAspectSupport.java
Labels: in: core, type: task

#22792 Some trivial optimization in method populateBean()
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractAutowireCapableBeanFactory.java
Labels: in: core, type: enhancement

#22816 Temporal should be simple value type like Date
  spring-beans/src/main/java/org/springframework/beans/BeanUtils.java
Labels: in: core, status: feedback-provided

#22829 Avoid possible memory leak in ResolvableType
  spring-core/src/main/java/org/springframework/core/ResolvableType.java
Labels: status: waiting-for-triage
