Repository spring-projects/spring-framework, pull requests merged in 2019-10, with the labels that each got.

#23739 Fix typo in web-uris doc
  src/docs/asciidoc/web/web-uris.adoc
Labels: type: documentation

#23746 Fixes broken links to dev.java.net
  src/docs/asciidoc/core/core-aop.adoc
  src/docs/asciidoc/web/webmvc-view.adoc
Labels: type: documentation

#23762 Fix typo in rsocket doc
  src/docs/asciidoc/rsocket.adoc
Labels: type: documentation

#23872 Stop Created-By manifest header from causing a test task cache miss
  gradle/spring-module.gradle
  integration-tests/integration-tests.gradle
Labels: type: task

#23864 TransactionalOperator::transactional does not close the transaction when cancelled
  spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionalOperatorImpl.java
Labels: in: data, type: bug

#23869 Extract build cache settings to a dedicated file
  buildSrc/settings.gradle
  gradle/build-cache-settings.gradle
  settings.gradle
Labels: type: task

#23873 Add tests for cancellation of transactional streams
  spring-tx/src/test/java/org/springframework/transaction/reactive/TransactionalOperatorTests.java
Labels: in: data, type: task

#23883 Add opt-in support for remote build cache and pushing to it from CI
  gradle/build-cache-settings.gradle
Labels: type: task

#23897 Fix Mockito deprecations
  spring-context/src/test/java/org/springframework/aop/aspectj/AfterReturningAdviceBindingTests.java
  spring-context/src/test/java/org/springframework/context/annotation/EnableLoadTimeWeavingTests.java
  spring-context/src/test/java/org/springframework/ejb/access/LocalStatelessSessionProxyFactoryBeanTests.java
  spring-context/src/test/java/org/springframework/ejb/access/SimpleRemoteStatelessSessionProxyFactoryBeanTests.java
  spring-core/src/test/java/org/springframework/util/concurrent/ListenableFutureTaskTests.java
  spring-messaging/src/test/java/org/springframework/messaging/rsocket/DefaultRSocketRequesterBuilderTests.java
  spring-messaging/src/test/java/org/springframework/messaging/simp/user/UserDestinationMessageHandlerTests.java
  spring-messaging/src/test/java/org/springframework/messaging/support/ExecutorSubscribableChannelTests.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/AbstractReactiveTransactionAspectTests.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/AbstractTransactionAspectTests.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/BeanFactoryTransactionTests.java
  spring-webflux/src/test/java/org/springframework/web/reactive/function/client/DefaultWebClientTests.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/HandlerExecutionChainTests.java
  spring-websocket/src/test/java/org/springframework/web/socket/messaging/StompSubProtocolHandlerTests.java
Labels: type: task
