Repository spring-projects/spring-framework, pull requests merged in 2020-03, with the labels that each got.

#24623 Fix typos in AbstractClientHttpRequest
  spring-web/src/main/java/org/springframework/http/client/reactive/AbstractClientHttpRequest.java
Labels: type: documentation

#24621 Fix formatting for pointcut expression examples in documentation
  src/docs/asciidoc/core/core-aop.adoc
Labels: type: documentation

#24620 Polish ReactorResourceFactory
  spring-web/src/main/java/org/springframework/http/client/reactive/ReactorResourceFactory.java
Labels: type: documentation

#24627 Fix typo in testing.adoc
  src/docs/asciidoc/testing.adoc
Labels: type: documentation

#24650 Update IntroductionInfo example in reference manual
  src/docs/asciidoc/core/core-aop-api.adoc
Labels: type: documentation

#24658 Fix ampersands in AOP examples in documentation
  src/docs/asciidoc/core/core-aop.adoc
Labels: type: task

#24631 Fix formatting in AOP examples in documentation
  src/docs/asciidoc/core/core-aop.adoc
Labels: type: task

#24667 Add logger.isInfoEnabled check before logger.info
  spring-aop/src/main/java/org/springframework/aop/framework/ProxyFactoryBean.java
Labels: in: core, type: task

#24672 Reduce String garbage in CglibAopProxy.doValidateClass()
  spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java
Labels: in: core, type: task

#24675 Remove unnecessary variable declaration in ProxyCallbackFilter
  spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java
Labels: in: core, type: task

#24686 Fix exception message in getMergedBeanDefinition
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanFactory.java
Labels: in: core, type: task

#24688 Improve Javadoc in AutoProxyRegistrar
  spring-context/src/main/java/org/springframework/context/annotation/AutoProxyRegistrar.java
Labels: in: core, type: documentation

#24645 Polish containsAny of CollectionUtils by reusing findFirstMatch
  spring-core/src/main/java/org/springframework/util/CollectionUtils.java
Labels: in: core, type: task

#24625 Add some test cases in StringUtilsTests
  spring-core/src/test/java/org/springframework/util/StringUtilsTests.java
Labels: in: core, type: task

#24691 Do not mention credentials as enabled by default in CorsRegistry
  spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/CorsRegistry.java
Labels: in: web, type: documentation

#24701 Fix typos in MergedAnnotationsCollectionTests
  spring-core/src/test/java/org/springframework/core/annotation/MergedAnnotationsCollectionTests.java
Labels: in: core, type: task

#24682 Improve javadoc in RollbackRuleAttribute regarding nested classes
  spring-tx/src/main/java/org/springframework/transaction/interceptor/RollbackRuleAttribute.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/RollbackRuleTests.java
Labels: in: data, type: documentation

#24704 Avoid unnecessary sorting in AbstractHandlerMethodMapping
  spring-webmvc/src/main/java/org/springframework/web/servlet/handler/AbstractHandlerMethodMapping.java
Labels: in: web, type: enhancement

#24683 Extract isDebugEnabled() checks to local variables
  spring-jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
Labels: in: data, status: feedback-provided, type: task

#24717 Delete empty .gitignore file
  spring-instrument/src/test/java/.gitignore
Labels: type: task

#24740 Improve Javadoc in AnnotatedElementUtils
  spring-core/src/main/java/org/springframework/core/annotation/AnnotatedElementUtils.java
Labels: in: core, type: documentation

#24746 Fix typos in source files
  spring-context/src/test/java/org/springframework/aop/aspectj/generic/GenericParameterMatchingTests.java
  spring-core/src/test/java/org/springframework/core/annotation/AnnotationBackCompatibiltyTests.java
  spring-core/src/test/java/org/springframework/core/annotation/AnnotationTypeMappingsTests.java
  spring-messaging/src/main/java/org/springframework/messaging/handler/invocation/reactive/AbstractMethodMessageHandler.java
  spring-test/src/test/java/org/springframework/test/context/support/ActiveProfilesUtilsTests.java
  spring-test/src/test/java/org/springframework/test/context/support/DirtiesContextTestExecutionListenerTests.java
Labels: type: task

#24745 Missing nullability declarations for package web.socket.server.jetty
  spring-websocket/src/main/java/org/springframework/web/socket/server/jetty/JettyRequestUpgradeStrategy.java
  spring-websocket/src/main/java/org/springframework/web/socket/server/jetty/package-info.java
Labels: in: web, status: backported, type: bug

#24752 Declare proxyBeanMethods=false in JmsBootstrapConfiguration
  spring-jms/src/main/java/org/springframework/jms/annotation/JmsBootstrapConfiguration.java
Labels: in: messaging, type: enhancement

#24753 Improve Javadoc in @Configuration
  spring-context/src/main/java/org/springframework/context/annotation/Configuration.java
Labels: in: core, type: documentation

#24674 Improve performance of StringUtils#cleanPath
  spring-core/src/main/java/org/springframework/util/StringUtils.java
  spring-core/src/test/java/org/springframework/util/StringUtilsTests.java
Labels: in: core, type: enhancement

#24758 Fix empty domain handling in ResponseCookie
  spring-web/src/main/java/org/springframework/http/ResponseCookie.java
  spring-web/src/test/java/org/springframework/http/ResponseCookieTests.java
Labels: in: web, type: bug

#24774 Make resourceAnnotationTypes field final in CommonAnnotationBPP
  spring-context/src/main/java/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor.java
Labels: in: core, type: task

#24781 Fix typos and improve readability in Webflux documentation
  src/docs/asciidoc/web/webflux.adoc
Labels: type: documentation

#24789 Remove obsolete comment in BeanDefinitionParserDelegate
  spring-beans/src/main/java/org/springframework/beans/factory/xml/BeanDefinitionParserDelegate.java
Labels: in: core, type: task

#24790 Remove useless .gitignore files
  integration-tests/src/test/java/.gitignore
  spring-context-support/src/main/resources/.gitignore
  spring-websocket/src/main/resources/.gitignore
  spring-websocket/src/test/java/.gitignore
Labels: type: task

#24792 Fix broken link in Javadoc for DynamicPropertySource
  spring-test/src/main/java/org/springframework/test/context/DynamicPropertySource.java
Labels: in: test, type: task

#24793 Upgrade to Gradle Build Scan Plugin 3.2
  build.gradle
Labels: type: task

#24799 Remove unnecessary mem alloc in CollectingReaderEventListener
  spring-beans/src/testFixtures/java/org/springframework/beans/testfixture/beans/CollectingReaderEventListener.java
Labels: type: task

#24800 Set initialValue of NamedThreadLocal in XmlBeanDefinitionReader
  spring-beans/src/main/java/org/springframework/beans/factory/xml/XmlBeanDefinitionReader.java
Labels: in: core, type: task

#24796 Remove incorrect @Nullable in DynamicPropertiesContextCustomizer
  spring-test/src/main/java/org/springframework/test/context/support/DynamicPropertiesContextCustomizer.java
Labels: in: test, type: task

#24808 Replace anonymous inner classes with lambdas in tests
  spring-context/src/test/java/org/springframework/context/support/DefaultLifecycleProcessorTests.java
  spring-context/src/test/java/org/springframework/scheduling/annotation/EnableSchedulingTests.java
  spring-core/src/test/java/org/springframework/util/concurrent/SettableListenableFutureTests.java
  spring-jdbc/src/test/java/org/springframework/jdbc/datasource/embedded/EmbeddedDatabaseBuilderTests.java
  spring-messaging/src/test/java/org/springframework/messaging/simp/stomp/StompBrokerRelayMessageHandlerIntegrationTests.java
  spring-web/src/test/java/org/springframework/web/context/request/async/DeferredResultTests.java
  spring-web/src/test/java/org/springframework/web/context/request/async/WebAsyncManagerTimeoutTests.java
Labels: type: task

#24807 Use try-with-resource to close resources
  spring-core/src/main/java/org/springframework/core/io/support/PropertiesLoaderUtils.java
  spring-web/src/main/java/org/springframework/remoting/httpinvoker/AbstractHttpInvokerRequestExecutor.java
  spring-web/src/main/java/org/springframework/web/context/support/ServletContextResourcePatternResolver.java
Labels: type: task

#24804 Remove unnecessary assignment in PropertiesBeanDefinitionReader
  spring-beans/src/main/java/org/springframework/beans/factory/support/PropertiesBeanDefinitionReader.java
Labels: in: core, type: task

#24815 Fix typo in webflux-cors.adoc
  src/docs/asciidoc/web/webflux-cors.adoc
Labels: type: task
