Repository spring-projects/spring-framework, pull requests merged in 2020-11, with the labels that each got.

#26012 Improve URI/query strings sanitization
  spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/NamedParameterUtils.java
  spring-r2dbc/src/main/java/org/springframework/r2dbc/core/NamedParameterUtils.java
  spring-web/src/main/java/org/springframework/web/util/UriComponentsBuilder.java
  spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java
  spring-web/src/test/java/org/springframework/web/util/UriComponentsBuilderTests.java
  spring-web/src/test/java/org/springframework/web/util/UrlPathHelperTests.java
Labels: in: data, in: web, type: enhancement

#26017 Improve AdvisedSupport.getAdvisors()
  spring-aop/src/main/java/org/springframework/aop/framework/Advised.java
  spring-aop/src/main/java/org/springframework/aop/framework/AdvisedSupport.java
  spring-aop/src/main/java/org/springframework/aop/framework/AopProxyUtils.java
  spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java
  spring-aop/src/main/java/org/springframework/aop/framework/JdkDynamicAopProxy.java
Labels: in: core, type: enhancement

#26025 Add FullyQualifiedAnnotationBeanNameGenerator.INSTANCE
  spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassPostProcessor.java
  spring-context/src/main/java/org/springframework/context/annotation/FullyQualifiedAnnotationBeanNameGenerator.java
Labels: in: core, status: backported, type: bug

#25899 Avoid multiple volatile reads/writes in a row where only one is enough
  spring-aop/src/main/java/org/springframework/aop/aspectj/MethodInvocationProceedingJoinPoint.java
  spring-beans/src/main/java/org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor.java
  spring-context/src/main/java/org/springframework/cache/support/AbstractCacheManager.java
Labels: in: core, type: enhancement

#26044 Delete explicit type arguments that can be inferred
  spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/ViewResolverRegistry.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/RedirectView.java
Labels: in: web, type: task

#26050 Fix wrong reference in UrlPathHelper.removeSemicolonContentInternal()
  spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java
  spring-web/src/test/java/org/springframework/web/util/UrlPathHelperTests.java
Labels: in: web, type: bug

#26064 Simplify AbstractAspectJAdvice.isVariableName()
  spring-aop/src/main/java/org/springframework/aop/aspectj/AbstractAspectJAdvice.java
Labels: in: core, type: task

#26070 Polish Javadoc for InjectionMetadata.forElements()
  spring-beans/src/main/java/org/springframework/beans/factory/annotation/InjectionMetadata.java
Labels: in: core, type: task

#26076 Make tests meaningful in DefaultListableBeanFactoryTests
  spring-beans/src/test/java/org/springframework/beans/factory/DefaultListableBeanFactoryTests.java
Labels: in: core, type: task

#26098 Simplify AstUtils.getPropertyAccessorsToTry()
  spring-expression/src/main/java/org/springframework/expression/spel/ast/AstUtils.java
Labels: in: core, type: task

#25855 Update javax.mail reference to jakarta.mail
  src/docs/asciidoc/integration.adoc
Labels: type: documentation

#26101 Reduce overhead of char[] creation
  spring-aop/src/main/java/org/springframework/aop/aspectj/AspectJAdviceParameterNameDiscoverer.java
  spring-core/src/main/java/org/springframework/core/Conventions.java
  spring-web/src/main/java/org/springframework/http/ContentDisposition.java
  spring-web/src/main/java/org/springframework/http/ResponseCookie.java
  spring-web/src/main/java/org/springframework/http/server/DefaultPathContainer.java
  spring-web/src/main/java/org/springframework/web/util/HierarchicalUriComponents.java
  spring-web/src/main/java/org/springframework/web/util/UriComponents.java
  spring-web/src/main/java/org/springframework/web/util/pattern/LiteralPathElement.java
  spring-web/src/main/java/org/springframework/web/util/pattern/SingleCharWildcardedPathElement.java
Labels: in: core, in: web, type: enhancement

#26107 Re-use the isVariableName method
  spring-aop/src/main/java/org/springframework/aop/aspectj/AbstractAspectJAdvice.java
  spring-aop/src/main/java/org/springframework/aop/aspectj/AspectJAdviceParameterNameDiscoverer.java
  spring-aop/src/main/java/org/springframework/aop/aspectj/AspectJProxyUtils.java
Labels: in: core, type: task

#26121 Fail MethodFilter.and() immediately when null is passed
  spring-core/src/main/java/org/springframework/util/ReflectionUtils.java
Labels: in: core, type: task

#26122 Simplify XMLEventStreamWriter.writeEndElement()
  spring-core/src/main/java/org/springframework/util/xml/XMLEventStreamWriter.java
Labels: in: core, type: task

#26157 Remove unused package-private class o.s.w.u.p.SubSequence
  spring-web/src/main/java/org/springframework/web/util/pattern/SubSequence.java
Labels: in: web, type: task
