Repository spring-projects/spring-framework, pull requests merged in 2020-04, with the labels that each got.

#24841 Fix Javadoc in PathPattern
  spring-web/src/main/java/org/springframework/web/util/pattern/PathPattern.java
Labels: in: core, type: documentation

#24864 Using single string variable instead of string array to pass varargs
  spring-webmvc/src/test/java/org/springframework/web/context/XmlWebApplicationContextTests.java
Labels: type: task

#24870 Improve performance of StringUtils.deleteAny()
  spring-core/src/main/java/org/springframework/util/StringUtils.java
  spring-core/src/test/java/org/springframework/util/StringUtilsTests.java
Labels: in: core, type: enhancement

#24871 Honor overridden AcceptHeaderLocaleContextResolver.getDefaultLocale()
  spring-web/src/main/java/org/springframework/web/server/i18n/AcceptHeaderLocaleContextResolver.java
Labels: in: web, status: backported, type: enhancement

#24906 Fix typo in webflux-functional.adoc
  src/docs/asciidoc/web/webflux-functional.adoc
Labels: type: task

#24896 Fixed typos
  src/docs/asciidoc/core/core-beans.adoc
Labels: status: waiting-for-triage

#24921 Fix Javadoc link in DefaultCorsProcessor
  spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
  spring-web/src/main/java/org/springframework/web/cors/reactive/DefaultCorsProcessor.java
Labels: type: task

#24925 Simplify some control flow code
  spring-web/src/main/java/org/springframework/web/bind/support/WebRequestDataBinder.java
  spring-web/src/main/java/org/springframework/web/util/pattern/RegexPathElement.java
Labels: type: task

#24924 Avoid unnecessary String instantiation in StringUtils.deleteAny()
  spring-core/src/main/java/org/springframework/util/StringUtils.java
Labels: in: core, type: task

#24933 Simplify substring() usage in MimeTypeUtils
  spring-core/src/main/java/org/springframework/util/MimeTypeUtils.java
Labels: in: core, status: feedback-provided, type: task

#24968 Fix typo in webmvc-functional.adoc
  src/docs/asciidoc/web/webmvc-functional.adoc
Labels: type: task

#24946 Rid pointless wrapping with BufferedInputStream from class reading
  spring-core/src/main/java/org/springframework/core/type/classreading/SimpleMetadataReader.java
Labels: in: core, type: enhancement

#24947 Allow override of data binding in ModelAttributeMethodArgumentResolver
  spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/ModelAttributeMethodArgumentResolver.java
Labels: in: web, type: enhancement

#24900 Prevent setting parent bean factory to self
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanFactory.java
Labels: in: core, type: enhancement
