Repository spring-projects/spring-framework, pull requests merged in 2020-02, with the labels that each got.

#24471 Fix typo in StringUtils class
  spring-core/src/main/java/org/springframework/util/StringUtils.java
Labels: type: documentation

#24428 Test ObjectUtils.containsElement()
  spring-core/src/test/java/org/springframework/util/ObjectUtilsTests.java
Labels: type: task

#24476 Produce less String-related garbage when generating bean names
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanFactory.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/BeanDefinitionReaderUtils.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/BeanDefinitionValueResolver.java
Labels: type: task

#24403 Simplify GenericConversionService.getMatchableConverters()
  spring-core/src/main/java/org/springframework/core/convert/support/GenericConversionService.java
Labels: in: core, type: task

#24393 Add close() method in FileCopyUtils to reduce duplication
  spring-core/src/main/java/org/springframework/util/FileCopyUtils.java
Labels: in: core, type: task

#24396 Let BFAwareGeneratorStrategy extend ClassLoaderAwareGeneratorStrategy
  spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassEnhancer.java
Labels: in: core, type: task

#24385 Use try-with-resource in ScriptUtils
  spring-jdbc/src/main/java/org/springframework/jdbc/datasource/init/ScriptUtils.java
Labels: in: data, type: task

#24383 Use dedicated catch block for ScriptException
  spring-jdbc/src/main/java/org/springframework/jdbc/datasource/init/DatabasePopulatorUtils.java
Labels: in: data, type: task

#24484 Improve assertion message in PersistenceExceptionTranslationInterceptor
  spring-tx/src/main/java/org/springframework/dao/support/PersistenceExceptionTranslationInterceptor.java
Labels: in: core, status: feedback-provided, type: enhancement

#24481 Upgrade to Spring Asciidoctor Extensions 0.4.0.RELEASE
  gradle/docs.gradle
  src/docs/asciidoc/docinfo-footer.html
  src/docs/asciidoc/js/switch-language.js
Labels: type: documentation

#24512 Use Gradle Enterprise Conventions Plugin to configure build scans
  build.gradle
  gradle/build-scan-user-data.gradle
Labels: type: task

#24531 Correct formatting of MessageSource example in documentation
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: documentation

#24543 Polishing
  spring-aop/src/test/java/org/springframework/aop/aspectj/TrickyAspectJPointcutExpressionTests.java
  spring-beans/src/testFixtures/java/org/springframework/beans/testfixture/beans/CollectingReaderEventListener.java
  spring-context/src/main/java/org/springframework/cache/config/CacheAdviceParser.java
  spring-context/src/test/java/org/springframework/cache/concurrent/ConcurrentMapCacheTests.java
Labels: type: task

#24532 Polish some test classes by using predefined constants
  spring-web/src/test/java/org/springframework/http/RequestEntityTests.java
  spring-web/src/test/java/org/springframework/http/ResponseEntityTests.java
Labels: status: feedback-provided, type: task

#24552 Correct Ant-style Patterns example in documentation
  src/docs/asciidoc/core/core-resources.adoc
Labels: type: documentation

#24551 Fix javadoc in DependencyDescriptor
  spring-beans/src/main/java/org/springframework/beans/factory/config/DependencyDescriptor.java
Labels: type: documentation

#24555 Simplify code in spring-test by using Collections.addAll
  spring-test/src/main/java/org/springframework/test/web/servlet/htmlunit/HtmlUnitRequestBuilder.java
  spring-test/src/main/java/org/springframework/test/web/servlet/htmlunit/MockMvcWebConnectionBuilderSupport.java
Labels: in: test, status: feedback-provided, type: task

#24566 Fix typos in tests
  spring-core/src/test/java/org/springframework/core/annotation/AnnotationsScannerTests.java
  spring-core/src/test/java/org/springframework/core/annotation/MergedAnnotationsTests.java
Labels: type: task

#24577 Remove unnecessary semicolon in some enum classes
  spring-context/src/main/java/org/springframework/context/annotation/ScopedProxyMode.java
  spring-context/src/main/java/org/springframework/jmx/support/RegistrationPolicy.java
  spring-messaging/src/main/java/org/springframework/messaging/simp/SimpMessageType.java
  spring-orm/src/test/java/org/springframework/orm/jpa/hibernate/beans/BeanSource.java
  spring-webflux/src/main/java/org/springframework/web/reactive/socket/WebSocketMessage.java
Labels: status: waiting-for-triage

#24578 Fix formatting in webflux-webclient.adoc
  src/docs/asciidoc/web/webflux-webclient.adoc
Labels: type: documentation

#24581 BlockHoundIntegration for spring-core
  build.gradle
  spring-core/spring-core.gradle
  spring-core/src/main/java/org/springframework/core/ReactiveAdapterRegistry.java
  spring-core/src/main/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
  spring-core/src/test/java/org/springframework/core/SpringCoreBlockHoundIntegrationTests.java
Labels: in: core, type: enhancement

#24585 Improve documentation for @Autowired/@Value in @Configuration classes
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: documentation

#24586 Simplify some redundant code
  spring-expression/src/test/java/org/springframework/expression/spel/ConstructorInvocationTests.java
  spring-expression/src/test/java/org/springframework/expression/spel/ExpressionLanguageScenarioTests.java
  spring-expression/src/test/java/org/springframework/expression/spel/MethodInvocationTests.java
  spring-expression/src/test/java/org/springframework/expression/spel/PropertyAccessTests.java
  spring-expression/src/test/java/org/springframework/expression/spel/SpelDocumentationTests.java
  spring-messaging/src/test/java/org/springframework/messaging/handler/invocation/MethodMessageHandlerTests.java
  spring-orm/src/main/java/org/springframework/orm/jpa/ExtendedEntityManagerCreator.java
  spring-web/src/main/java/org/springframework/http/codec/protobuf/ProtobufDecoder.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/mvc/method/annotation/ServletAnnotationControllerHandlerMethodTests.java
Labels: type: task

#24597 Fix typo in reference manual
  src/docs/asciidoc/languages/kotlin.adoc
Labels: in: test, type: documentation

#24613 Fix typo in WebClient.Builder Javadoc
  spring-webflux/src/main/java/org/springframework/web/reactive/function/client/WebClient.java
Labels: in: web, type: task
