Repository spring-projects/spring-framework, pull requests merged in 2020-08, with the labels that each got.

#25464 Introduce CronExpression
  spring-context/src/main/java/org/springframework/scheduling/support/CronExpression.java
  spring-context/src/main/java/org/springframework/scheduling/support/CronField.java
  spring-context/src/main/java/org/springframework/scheduling/support/CronSequenceGenerator.java
  spring-context/src/main/java/org/springframework/scheduling/support/CronTrigger.java
  spring-context/src/test/java/org/springframework/scheduling/support/BitSetAssert.java
  spring-context/src/test/java/org/springframework/scheduling/support/CronExpressionTests.java
  spring-context/src/test/java/org/springframework/scheduling/support/CronFieldTests.java
  spring-context/src/test/java/org/springframework/scheduling/support/CronTriggerTests.java
Labels: in: core, type: enhancement

#25555 Remove @Nullable from CookieLocaleResolver#determineDefaultLocale()
  spring-webmvc/src/main/java/org/springframework/web/servlet/i18n/CookieLocaleResolver.java
Labels: status: waiting-for-triage

#25401 Improve UriComponents.sanitizeSource()
  spring-web/src/main/java/org/springframework/web/util/UriComponents.java
Labels: in: web, type: enhancement

#25585 Eliminate unnecessary word in core-bean.adoc that causes repetition
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: documentation, type: task

#25646 Fix appendix typos in ContentDisposition
  spring-web/src/main/java/org/springframework/http/ContentDisposition.java
Labels: type: task

#25651 Add logPrefix to the log statement
  spring-webflux/src/main/java/org/springframework/web/reactive/result/HandlerResultHandlerSupport.java
Labels: in: web, type: task

#25660 Improve performance of JdkDynamicAopProxy.getProxy(ClassLoader)
  spring-aop/src/main/java/org/springframework/aop/framework/JdkDynamicAopProxy.java
  spring-core/src/main/java/org/springframework/util/ReflectionUtils.java
Labels: in: core, type: enhancement

#25666 gh-25650 Replace remaining usage of LinkedList with ArrayList in tests
  spring-aop/src/test/java/org/springframework/aop/aspectj/annotation/AbstractAspectJAdvisorFactoryTests.java
  spring-beans/src/test/java/org/springframework/beans/AbstractPropertyAccessorTests.java
  spring-beans/src/test/java/org/springframework/beans/BeanWrapperGenericsTests.java
  spring-beans/src/test/java/org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessorTests.java
  spring-beans/src/test/java/org/springframework/beans/factory/config/SimpleScopeTests.java
  spring-beans/src/test/java/org/springframework/beans/factory/support/BeanFactoryGenericsTests.java
  spring-context-support/src/test/java/org/springframework/validation/beanvalidation2/SpringValidatorAdapterTests.java
  spring-context-support/src/test/java/org/springframework/validation/beanvalidation2/ValidatorFactoryTests.java
  spring-context/src/test/java/org/springframework/aop/framework/AbstractAopProxyTests.java
  spring-context/src/test/java/org/springframework/aop/framework/ProxyFactoryBeanTests.java
  spring-context/src/test/java/org/springframework/context/annotation/ImportSelectorTests.java
  spring-context/src/test/java/org/springframework/context/event/ApplicationContextEventTests.java
  spring-context/src/test/java/org/springframework/validation/beanvalidation/SpringValidatorAdapterTests.java
  spring-context/src/test/java/org/springframework/validation/beanvalidation/ValidatorFactoryTests.java
  spring-core/src/test/java/org/springframework/core/convert/converter/DefaultConversionServiceTests.java
  spring-core/src/test/java/org/springframework/core/convert/support/CollectionToCollectionConverterTests.java
  spring-core/src/test/java/org/springframework/util/AutoPopulatingListTests.java
  spring-core/src/test/java/org/springframework/util/ClassUtilsTests.java
  spring-core/src/test/java/org/springframework/util/CollectionUtilsTests.java
  spring-core/src/test/java/org/springframework/util/ReflectionUtilsTests.java
  spring-jdbc/src/test/java/org/springframework/jdbc/core/JdbcTemplateTests.java
  spring-jdbc/src/test/java/org/springframework/jdbc/core/namedparam/NamedParameterJdbcTemplateTests.java
  spring-test/src/test/java/org/springframework/mock/web/MockMultipartHttpServletRequestTests.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/RuleBasedTransactionAttributeTests.java
  spring-tx/src/test/java/org/springframework/transaction/jta/MockUOWManager.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/mvc/method/annotation/ServletAnnotationControllerHandlerMethodTests.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/tags/UrlTagTests.java
  spring-webmvc/src/test/java/org/springframework/web/servlet/tags/form/SelectTagTests.java
Labels: type: task
