Repository spring-projects/spring-framework, pull requests merged in 2020-07, with the labels that each got.

#25361 Remove redundant Character.toLowerCase() in BeanPropertyRowMapper
  spring-jdbc/src/main/java/org/springframework/jdbc/core/BeanPropertyRowMapper.java
Labels: in: data, type: enhancement

#25368 Use correct link to MaxInMemorySize
  src/docs/asciidoc/web/webflux.adoc
Labels: type: documentation

#25396 Fix typo in javadoc
  spring-web/src/main/java/org/springframework/web/bind/annotation/RequestMapping.java
Labels: in: web, type: documentation

#25452 Use `static private` instead of `private static` for method declarations
  spring-core/src/main/java/org/springframework/core/MethodParameter.java
  spring-messaging/src/main/java/org/springframework/messaging/handler/invocation/reactive/AbstractEncoderMethodReturnValueHandler.java
  spring-tx/src/main/java/org/springframework/transaction/interceptor/TransactionAspectSupport.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/AbstractMessageWriterResultHandler.java
Labels: type: task

#25453 Use Stream#toArray in TestCompiler
  spring-context-indexer/src/test/java/org/springframework/context/index/test/TestCompiler.java
Labels: type: task

#25458 Fix typos in Javadoc
  spring-r2dbc/src/main/java/org/springframework/r2dbc/core/DatabaseClient.java
  spring-r2dbc/src/main/java/org/springframework/r2dbc/core/QueryOperation.java
Labels: in: data, type: task

#25450 Use StringBuilder instead of StringBuffer in tests
  spring-aop/src/test/java/org/springframework/aop/aspectj/AspectJAdviceParameterNameDiscovererTests.java
Labels: type: task

#25448 Fix links in Javadoc
  spring-beans/src/test/java/org/springframework/beans/factory/xml/DuplicateBeanIdTests.java
  spring-context/src/test/java/org/springframework/aop/framework/AbstractAopProxyTests.java
  spring-core/src/main/java/org/springframework/core/env/ReadOnlySystemAttributesMap.java
  spring-core/src/test/java/org/springframework/core/annotation/AnnotatedElementUtilsTests.java
  spring-core/src/test/java/org/springframework/core/annotation/MultipleComposedAnnotationsOnSingleAnnotatedElementTests.java
  spring-web/src/main/java/org/springframework/http/codec/protobuf/ProtobufDecoder.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/tiles3/AbstractSpringPreparerFactory.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/tiles3/SimpleSpringPreparerFactory.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/tiles3/SpringBeanPreparerFactory.java
Labels: status: feedback-provided, type: documentation

#25449 Simplify if-statements with instanceof checks
  spring-beans/src/testFixtures/java/org/springframework/beans/testfixture/beans/TestBean.java
  spring-context-indexer/src/main/java/org/springframework/context/index/processor/TypeHelper.java
  spring-context/src/main/java/org/springframework/cache/annotation/SpringCacheAnnotationParser.java
  spring-expression/src/main/java/org/springframework/expression/spel/ast/OperatorInstanceof.java
  spring-test/src/main/java/org/springframework/test/context/web/AbstractGenericWebContextLoader.java
  spring-tx/src/main/java/org/springframework/transaction/annotation/Ejb3TransactionAnnotationParser.java
  spring-tx/src/main/java/org/springframework/transaction/annotation/JtaTransactionAnnotationParser.java
  spring-tx/src/main/java/org/springframework/transaction/annotation/SpringTransactionAnnotationParser.java
  spring-web/src/main/java/org/springframework/web/util/pattern/PathPattern.java
  spring-websocket/src/main/java/org/springframework/web/socket/config/WebSocketMessageBrokerStats.java
Labels: status: feedback-provided, type: task

#25447 Use System.currentTimeMillis() in AbstractSockJsService
  spring-websocket/src/main/java/org/springframework/web/socket/sockjs/support/AbstractSockJsService.java
Labels: in: web, status: feedback-provided, type: enhancement

#25456 Use Integer.parseInt instead of Integer.valueOf for primitive int
  spring-aspects/src/test/java/org/springframework/cache/aspectj/AbstractCacheAnnotationTests.java
  spring-context/src/test/java/org/springframework/cache/config/EnableCachingIntegrationTests.java
  spring-context/src/testFixtures/java/org/springframework/context/testfixture/cache/AbstractCacheAnnotationTests.java
  spring-core/src/test/java/org/springframework/util/xml/TransformerUtilsTests.java
  spring-websocket/src/test/java/org/springframework/web/socket/sockjs/client/SockJsUrlInfoTests.java
Labels: type: task

#25495 Disable unwanted Kotlin Stdlib dependencies
  gradle.properties
Labels: status: waiting-for-triage
