Repository spring-projects/spring-framework, pull requests merged in 2020-05, with the labels that each got.

#24890 Extend transaction attributes with labels
  spring-tx/src/main/java/org/springframework/transaction/annotation/SpringTransactionAnnotationParser.java
  spring-tx/src/main/java/org/springframework/transaction/annotation/Transactional.java
  spring-tx/src/main/java/org/springframework/transaction/interceptor/DefaultTransactionAttribute.java
  spring-tx/src/main/java/org/springframework/transaction/interceptor/DelegatingTransactionAttribute.java
  spring-tx/src/main/java/org/springframework/transaction/interceptor/TransactionAttribute.java
  spring-tx/src/test/java/org/springframework/transaction/annotation/AnnotationTransactionAttributeSourceTests.java
  src/docs/asciidoc/data-access.adoc
Labels: in: data, type: enhancement

#25021 Fix @Transactional syntax error in reference manual
  src/docs/asciidoc/data-access.adoc
Labels: type: task

#25040 Fix typo in core-beans.adoc
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: task

#25038 Use Map::computeIfAbsent to simplify scope implementations
  spring-context/src/main/java/org/springframework/context/support/SimpleThreadScope.java
  spring-tx/src/main/java/org/springframework/transaction/support/SimpleTransactionScope.java
Labels: in: core, type: task

#25051 Fix typo in RmiSupportTests
  spring-context/src/test/java/org/springframework/remoting/rmi/RmiSupportTests.java
Labels: type: task

#25054 Use computeIfAbsent in ResourceBundleMessageSource
  spring-context/src/main/java/org/springframework/context/support/ResourceBundleMessageSource.java
Labels: type: task

#25056 Avoid StringBuilder.append(Object) in ContentDisposition
  spring-web/src/main/java/org/springframework/http/ContentDisposition.java
Labels: type: task

#25045 Fix SpelEvaluationException with example code
  src/docs/asciidoc/core/core-expressions.adoc
Labels: in: core, type: documentation
