Repository spring-projects/spring-framework, pull requests merged in 2020-12, with the labels that each got.

#26197 Polish ConfigurationClassPostProcessorTests
  spring-context/src/test/java/org/springframework/context/annotation/ConfigurationClassPostProcessorTests.java
Labels: in: core, type: task

#26211 Correct satisfies statements in SpelParserTests.generalExpressions
  spring-expression/src/test/java/org/springframework/expression/spel/standard/SpelParserTests.java
Labels: in: core, type: task

#26217 Fix punctuation typo in javadoc for ResponseExtractor
  spring-web/src/main/java/org/springframework/web/client/ResponseExtractor.java
Labels: in: web, type: task

#26237 Remove duplicate "property" in PropertyCacheKey.toString()
  spring-expression/src/main/java/org/springframework/expression/spel/support/ReflectivePropertyAccessor.java
Labels: in: core, type: bug

#26254 Fix typo in Javadoc for AbstractJdbcCall
  spring-jdbc/src/main/java/org/springframework/jdbc/core/simple/AbstractJdbcCall.java
Labels: type: task

#26260 Replace AtomicReference<Boolean> with AtomicBoolean in AbstractServerHttpResponse.writeWith()
  spring-web/src/main/java/org/springframework/http/server/reactive/AbstractServerHttpResponse.java
Labels: in: web, type: task
