Repository spring-projects/spring-framework, pull requests merged in 2021-02, with the labels that each got.

#26484 Fix Javadoc in StandardServletAsyncWebRequest
  spring-web/src/main/java/org/springframework/web/context/request/async/StandardServletAsyncWebRequest.java
Labels: in: web, type: task

#26487 Add application/vnd.google.protobuf to supported Mime Type of Protobuf Codec
  spring-web/src/main/java/org/springframework/http/codec/protobuf/ProtobufCodecSupport.java
Labels: in: web, type: task

#26519 Simplify BeanUtils.findPrimaryConstructor()
  spring-beans/src/main/java/org/springframework/beans/BeanUtils.java
Labels: in: core, type: task

#26418 Close mapping streams after the ValidatorFactory has been built in LocalValidatorFactoryBean
  spring-context/src/main/java/org/springframework/validation/beanvalidation/LocalValidatorFactoryBean.java
Labels: in: core, status: backported, type: enhancement

#26471 Avoid unnecessary wrapping for SqlParameterValue
  spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/NamedParameterUtils.java
  spring-jdbc/src/test/java/org/springframework/jdbc/core/namedparam/NamedParameterUtilsTests.java
Labels: in: data, type: regression

#26551 Fix typo in @Configurable example in reference manual
  src/docs/asciidoc/core/core-aop.adoc
Labels: type: task

#26556 Fix build output directory for ref docs in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type: documentation

#26568 Fix Javadoc link in DynamicIntroductionAdvice
  spring-aop/src/main/java/org/springframework/aop/DynamicIntroductionAdvice.java
Labels: in: core, type: task

#26586 Polish contribution
  spring-core/src/main/java/org/springframework/core/env/StandardEnvironment.java
  spring-core/src/test/java/org/springframework/core/env/CustomEnvironmentTests.java
  spring-web/src/main/java/org/springframework/web/context/support/StandardServletEnvironment.java
Labels: in: core, type: task

#26592 Fix MockHttpServletRequest reference in Javadoc
  spring-test/src/main/java/org/springframework/mock/web/MockHttpServletMapping.java
Labels: type: task

#26595 Add vscode folder to .gitignore
  .gitignore
Labels: type: task

#26574 ClassLoader.getResource can throw IllegalArgumentException
  spring-core/src/main/java/org/springframework/core/io/ClassPathResource.java
Labels: in: core, status: backported, type: bug

#26575 Fix handling of "file:" paths to non-existent files on Windows
  spring-beans/src/main/java/org/springframework/beans/propertyeditors/PathEditor.java
  spring-beans/src/test/java/org/springframework/beans/propertyeditors/PathEditorTests.java
Labels: in: core, status: backported, type: bug

#26613 Add missing nullable annotation to ResponseEntity ok convenience method
  spring-web/src/main/java/org/springframework/http/ResponseEntity.java
Labels: in: web, type: enhancement
