Repository spring-projects/spring-framework, pull requests merged in 2021-12, with the labels that each got.

#27716 Support SQUARE brackets [] around NAMED parameter
  spring-r2dbc/src/main/java/org/springframework/r2dbc/core/NamedParameterUtils.java
  spring-r2dbc/src/test/java/org/springframework/r2dbc/core/NamedParameterUtilsUnitTests.java
Labels: in: data, type: enhancement

#27726 Clarify that interface-level cache annotations work for target-class proxies as well
  spring-context/src/test/java/org/springframework/cache/config/EnableCachingIntegrationTests.java
  src/docs/asciidoc/integration.adoc
Labels: type: documentation, in: core

#27700 Apply "instanceof pattern matching" in spring-beans
  spring-beans/src/main/java/org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor.java
  spring-beans/src/main/java/org/springframework/beans/factory/config/ConstructorArgumentValues.java
  spring-beans/src/main/java/org/springframework/beans/factory/config/CustomScopeConfigurer.java
  spring-beans/src/main/java/org/springframework/beans/factory/groovy/GroovyBeanDefinitionReader.java
  spring-beans/src/main/java/org/springframework/beans/factory/groovy/GroovyBeanDefinitionWrapper.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultListableBeanFactory.java
  spring-beans/src/main/java/org/springframework/beans/propertyeditors/CustomCollectionEditor.java
  spring-beans/src/main/java/org/springframework/beans/propertyeditors/CustomMapEditor.java
Labels: type: task
