Repository spring-projects/spring-framework, pull requests merged in 2021-03, with the labels that each got.

#26622 Fix @EventListener example in reference manual
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: task

#26635 Add RouterFunctionMapping to Javadoc for WebMvcConfigurationSupport
  spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java
Labels: in: web, type: task

#26640 Fixed typo in ref docs
  src/docs/asciidoc/core/core-validation.adoc
Labels: type: task

#26634 Optimize initialization size of temporary ArrayLists in ReflectionUtils
  spring-core/src/main/java/org/springframework/util/ReflectionUtils.java
Labels: in: core, type: task

#26639 Reduce memory consumption of buildAdvisors
  spring-aop/src/main/java/org/springframework/aop/framework/autoproxy/AbstractAutoProxyCreator.java
Labels: in: core, type: task

#26658 StatusAssertion value methods fail when used with custom status code
  spring-test/src/main/java/org/springframework/test/web/reactive/server/StatusAssertions.java
  spring-test/src/test/java/org/springframework/test/web/reactive/server/StatusAssertionTests.java
Labels: in: test, in: web, type: bug

#26442 Introduce 'idleReceivesPerTaskLimit' in DefaultMessageListenerContainer
  spring-jms/src/main/java/org/springframework/jms/listener/DefaultMessageListenerContainer.java
Labels: in: messaging, type: enhancement

#26680 Add support for Oracle bind marker scheme using R2DBC
  spring-r2dbc/src/main/java/org/springframework/r2dbc/core/binding/BindMarkersFactoryResolver.java
  spring-r2dbc/src/test/java/org/springframework/r2dbc/core/binding/BindMarkersFactoryResolverUnitTests.java
Labels: in: data, type: enhancement

#26676 Remove duplicate word in Javadoc
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanDefinition.java
Labels: type: task

#26675 Polish
  spring-web/src/main/java/org/springframework/http/ResponseEntity.java
  spring-web/src/test/java/org/springframework/web/server/session/HeaderWebSessionIdResolverTests.java
Labels: type: task

#26732 Polish web docs example
  src/docs/asciidoc/web/webflux.adoc
  src/docs/asciidoc/web/webmvc.adoc
Labels: type: task
