Repository spring-projects/spring-framework, pull requests merged in 2021-05, with the labels that each got.

#26893 Fix MethodMatcher API doc description
  src/docs/asciidoc/core/core-aop-api.adoc
Labels: type: task

#26938 Fix punctuation in Custom Cache Resolution section of ref docs
  src/docs/asciidoc/integration.adoc
Labels: type: task

#26960 Polish
  spring-web/src/main/java/org/springframework/web/context/support/SpringBeanAutowiringSupport.java
  src/docs/asciidoc/web/webmvc.adoc
Labels: type: task

#26951 Polish PORT_PATTERN in UriComponentsBuilder
  spring-web/src/main/java/org/springframework/web/util/UriComponentsBuilder.java
Labels: in: web, type: enhancement

#26968 Refactor ConcurrentBeanWrapperTests to use @RepeatedTest
  spring-beans/src/test/java/org/springframework/beans/ConcurrentBeanWrapperTests.java
Labels: type: task

#26871 Add ApplicationEvent constructor for specifying timestamp
  spring-context/src/main/java/org/springframework/context/ApplicationEvent.java
Labels: in: core, in: test, type: enhancement

#27001 Fix @Transactional docs regarding method visibility
  src/docs/asciidoc/data-access.adoc
Labels: in: data, type: documentation
