Repository spring-projects/spring-framework, pull requests merged in 2021-08, with the labels that each got.

#27298 Fix grammatical errors in Javadoc
  spring-aop/src/main/java/org/aopalliance/intercept/Joinpoint.java
  spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java
  spring-webflux/src/main/java/org/springframework/web/reactive/function/server/RequestPredicate.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/function/RequestPredicate.java
  spring-websocket/src/main/java/org/springframework/web/socket/adapter/standard/ConvertingEncoderDecoderSupport.java
Labels: type: task

#27303 Fix UrlPathHelper#shouldRemoveSemicolonContent()
  spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java
  spring-web/src/test/java/org/springframework/web/util/UrlPathHelperTests.java
Labels: in: web, type: bug, status: feedback-provided

#27337 Fix Kotlin example for filtering handler functions
  src/docs/asciidoc/web/webmvc-functional.adoc
Labels: type: documentation, in: web

#27336 Remove unused private loggers
  spring-context/src/test/java/org/springframework/aop/aspectj/autoproxy/AspectJAutoProxyCreatorTests.java
  spring-context/src/test/java/org/springframework/context/expression/ApplicationContextExpressionTests.java
  spring-tx/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
  spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java
Labels: type: task

#27339 Remove unnecessary brace in WebSocket documenation
  src/docs/asciidoc/web/websocket.adoc
Labels: type: task

#27340 Polish AbstractAspectJAdvisorFactory
  spring-aop/src/main/java/org/springframework/aop/aspectj/annotation/AbstractAspectJAdvisorFactory.java
Labels: type: task
