Repository spring-projects/spring-framework, pull requests merged in 2021-01, with the labels that each got.

#26436 Fix typo in URI Encoding section of reference docs
  src/docs/asciidoc/web/web-uris.adoc
Labels: type: task

#26446 Fix DelegatingWebMvcConfigurationTests.configurePathPatternParser()
  spring-webmvc/src/test/java/org/springframework/web/servlet/config/annotation/DelegatingWebMvcConfigurationTests.java
Labels: in: test, type: task

#26450 Add Javadoc @since tag to TransactionSynchronizationUtils.unwrapResourceIfNecessary()
  spring-tx/src/main/java/org/springframework/transaction/support/TransactionSynchronizationUtils.java
Labels: type: task

#26468 Fix ContentCachingResponseWrapper comment typo
  spring-web/src/main/java/org/springframework/web/util/ContentCachingResponseWrapper.java
Labels: status: waiting-for-triage
