Repository spring-projects/spring-framework, pull requests merged in 2021-04, with the labels that each got.

#26782 Update documentation for <context:annotation-config/>
  src/docs/asciidoc/core/core-appendix.adoc
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: documentation

#26783 Update ref docs regarding RequiredAnnotationBeanPostProcessor registration
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: documentation

#26779 Allow spring-expression to be more easily repackaged for embedding in third-party JARs
  spring-expression/src/main/java/org/springframework/expression/spel/standard/SpelCompiler.java
Labels: in: core, type: enhancement

#26812 Update FormatterRegistry interface in reference manual
  src/docs/asciidoc/core/core-validation.adoc
Labels: type: task

#26816 Fix LocaleEditor description and formatting in reference manual
  src/docs/asciidoc/core/core-validation.adoc
Labels: type: task

#26825 Remove reference to Joda Time support in @DateTimeFormat Javadoc
  spring-context/src/main/java/org/springframework/format/annotation/DateTimeFormat.java
Labels: type: task

#26832 Fix formatting for PersonValidator Kotlin example in ref docs
  src/docs/asciidoc/core/core-validation.adoc
Labels: type: task

#26797 Improve ref docs regarding @Bean method visibility constraints
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: task

#26823 Remove reference to Commons Collections in ColumnMapRowMapper Javadoc
  spring-jdbc/src/main/java/org/springframework/jdbc/core/ColumnMapRowMapper.java
Labels: type: task

#26836 Fix Kotlin code formatting for Inline Maps section of ref docs
  src/docs/asciidoc/core/core-expressions.adoc
Labels: type: task

#26822 Use String.startsWith() instead of String.substring() in PatternMatchUtils
  spring-core/src/main/java/org/springframework/util/PatternMatchUtils.java
Labels: in: core, type: enhancement

#26758 Update FactoryBean generic description in ref docs
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: task

#26846 Improve documentation for SpEL constructor support
  src/docs/asciidoc/core/core-expressions.adoc
Labels: type: task

#26865 Fix MessageSource doc description
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: task

#26862 Fix aspect autodetection description
  src/docs/asciidoc/core/core-aop.adoc
Labels: type: task

#26852 Fix SpEL selection description in ref docs
  src/docs/asciidoc/core/core-expressions.adoc
Labels: type: task

#26878 Polish
  spring-aop/src/main/java/org/springframework/aop/framework/autoproxy/AbstractAutoProxyCreator.java
  spring-context/src/main/java/org/springframework/validation/annotation/ValidationAnnotationUtils.java
  spring-context/src/test/java/org/springframework/format/datetime/DateFormattingTests.java
  spring-test/src/test/java/org/springframework/mock/web/MockHttpServletResponseTests.java
  spring-webflux/src/main/java/org/springframework/web/reactive/function/client/ExchangeFunction.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/FrameworkServlet.java
Labels: type: task

#26876 Fix syntax for RequestEntity headers example in ref docs
  src/docs/asciidoc/integration.adoc
Labels: type: task

#26874 Improve readability of MessageSourceSupport Javadoc
  spring-context/src/main/java/org/springframework/context/support/MessageSourceSupport.java
Labels: type: task

#26875 Use an import instead of FQCN in StaxEventXMLReader
  spring-core/src/main/java/org/springframework/util/xml/StaxEventXMLReader.java
Labels: type: task

#26773 Fix @Scope documentation in ref docs
  src/docs/asciidoc/core/core-beans.adoc
Labels: type: task
