Repository spring-projects/spring-framework, pull requests merged in 2022-05, with the labels that each got.

#28427 Use Arrays.toString for initMethodNames and destroyMethodNames arrays in AbstractBeanDefinition#toString
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanDefinition.java
Labels: type: bug, in: core

#28431 Fix typo in declarative HTTP interfaces docs
  src/docs/asciidoc/integration.adoc
Labels: type: task

#28426 Polish Javadoc and inline comments
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanFactory.java
  spring-test/src/main/java/org/springframework/test/context/ContextConfiguration.java
Labels: type: task

#28461 Use getHost instead of getContainerIpAddress in Redis examples
  spring-test/src/main/java/org/springframework/test/context/DynamicPropertySource.java
  src/docs/asciidoc/testing.adoc
Labels: status: waiting-for-triage, in: test, type: documentation
