Repository spring-projects/spring-framework, pull requests merged in 2022-11, with the labels that each got.

#29434 TomcatRequestUpgradeStrategy is not compatible with Tomcat 10.1
  spring-webflux/src/main/java/org/springframework/web/reactive/socket/server/upgrade/TomcatRequestUpgradeStrategy.java
  spring-websocket/src/main/java/org/springframework/web/socket/server/standard/TomcatRequestUpgradeStrategy.java
Labels: in: web, type: bug

#29493 Assert fixed in DefaultErrorResponseBuilder
  spring-web/src/main/java/org/springframework/web/DefaultErrorResponseBuilder.java
Labels: type: task

#29456 Fix a syntax error in an XML listing in core-validation.adoc
  framework-docs/src/docs/asciidoc/core/core-validation.adoc
Labels: type: documentation

#29551 Fix Javadoc link text in BindingResult
  spring-context/src/main/java/org/springframework/validation/BindingResult.java
Labels: type: documentation

#29590 Fix typo in observability documentation
  framework-docs/src/docs/asciidoc/integration/observability.adoc
Labels: type: documentation
