Repository spring-projects/spring-framework, pull requests merged in 2023-11, with the labels that each got.

#31587 Link to KDoc API documentation from Javadoc overview
  framework-api/framework-api.gradle
  framework-docs/src/docs/api/dokka-overview.md
  framework-docs/src/docs/api/overview.html
Labels: type: documentation, type: task

#30534 Always fall back to original method if annotation pointcut used
  spring-aop/src/main/java/org/springframework/aop/aspectj/AspectJExpressionPointcut.java
  spring-aop/src/test/java/org/springframework/aop/aspectj/AspectJExpressionPointcutTests.java
Labels: type: bug, in: core

#31701 Docs build version updates
  antora-playbook.yml
  build.gradle
Labels: type: task
