Repository spring-projects/spring-framework, pull requests merged in 2023-06, with the labels that each got.

#30619 Handle custom JMS acknowledgment modes as client acknowledge
  spring-jms/src/main/java/org/springframework/jms/support/JmsAccessor.java
  spring-jms/src/test/java/org/springframework/jms/support/JmsAccessorTests.java
Labels: in: messaging, type: enhancement

#30673 Upgrade to spring-doc-actions 0.0.8
  .github/workflows/deploy-docs.yml
Labels: type: task

#30668 Ensure Spring `LogFactory` contains all public methods from Apache `LogFactory`
  spring-jcl/src/main/java/org/apache/commons/logging/LogFactory.java
Labels: in: core, type: enhancement, for: backport-to-5.3.x

#30776 Fix log level on error with @TransactionalEventListener
  spring-tx/src/main/java/org/springframework/transaction/support/TransactionSynchronizationUtils.java
Labels: in: data, status: backported, type: regression

#30785 Polish gh-30013
  spring-context/src/main/java/org/springframework/scheduling/config/DefaultScheduledTaskObservationConvention.java
  spring-context/src/main/java/org/springframework/scheduling/config/ScheduledTaskObservationContext.java
  spring-context/src/main/java/org/springframework/scheduling/config/ScheduledTaskObservationConvention.java
  spring-context/src/main/java/org/springframework/scheduling/config/ScheduledTaskObservationDocumentation.java
  spring-context/src/main/java/org/springframework/scheduling/config/ScheduledTaskRegistrar.java
  spring-context/src/main/java/org/springframework/scheduling/support/ScheduledMethodRunnable.java
  spring-web/src/main/java/org/springframework/web/server/adapter/HttpWebHandlerAdapter.java
  spring-web/src/main/java/org/springframework/web/server/adapter/WebHttpHandlerBuilder.java
  spring-web/src/main/java/org/springframework/web/server/handler/ExceptionHandlingWebHandler.java
  spring-web/src/test/java/org/springframework/web/server/adapter/HttpWebHandlerAdapterObservabilityTests.java
Labels: type: task
