Repository spring-projects/spring-framework, pull requests merged in 2023-02, with the labels that each got.

#29703 Release R2DBC connection when cleanup fails in transaction
  spring-r2dbc/src/main/java/org/springframework/r2dbc/connection/R2dbcTransactionManager.java
  spring-r2dbc/src/test/java/org/springframework/r2dbc/connection/R2dbcTransactionManagerUnitTests.java
Labels: in: data, type: enhancement

#29557 Restrict forwards in MockMvcWebConnection to 100
  spring-test/src/main/java/org/springframework/test/web/servlet/htmlunit/MockMvcWebConnection.java
  spring-test/src/test/java/org/springframework/test/web/servlet/htmlunit/ForwardController.java
  spring-test/src/test/java/org/springframework/test/web/servlet/htmlunit/MockMvcWebConnectionTests.java
Labels: in: test, in: web, type: enhancement

#29975 Polish
  framework-docs/src/docs/asciidoc/web/webmvc.adoc
  spring-context/src/test/kotlin/org/springframework/context/aot/KotlinReflectionBeanRegistrationAotProcessorTests.kt
  spring-context/src/test/kotlin/org/springframework/validation/beanvalidation/KotlinMethodValidationTests.kt
  spring-core/src/main/java/org/springframework/cglib/core/TinyBitSet.java
  spring-core/src/main/java/org/springframework/core/annotation/RepeatableContainers.java
  spring-core/src/main/java/org/springframework/core/codec/ResourceDecoder.java
  spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java
  spring-core/src/main/kotlin/org/springframework/aot/hint/TypeHintExtensions.kt
  spring-core/src/test/kotlin/org/springframework/aot/hint/ResourceHintsExtensionsTests.kt
  spring-r2dbc/src/test/java/org/springframework/r2dbc/connection/R2dbcTransactionManagerUnitTests.java
  spring-test/src/main/java/org/springframework/test/web/servlet/htmlunit/MockMvcWebConnection.java
  spring-test/src/test/java/org/springframework/test/web/servlet/htmlunit/MockMvcWebConnectionTests.java
  spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java
  spring-web/src/test/java/org/springframework/http/ResponseEntityTests.java
  spring-web/src/test/kotlin/org/springframework/web/method/annotation/ModelAttributeMethodProcessorKotlinTests.kt
  spring-webflux/src/main/java/org/springframework/web/reactive/function/client/DefaultClientRequestObservationConvention.java
  spring-webflux/src/test/kotlin/org/springframework/web/reactive/function/client/support/KotlinWebClientHttpServiceProxyTests.kt
  spring-webmvc/src/test/java/org/springframework/web/servlet/mvc/method/RequestMappingInfoHandlerMappingTests.java
Labels: type: task

#29986 Fix Javadoc `@since` tags for MockRestRequestMatchers queryParam() and header()
  spring-test/src/main/java/org/springframework/test/web/client/match/MockRestRequestMatchers.java
Labels: in: test, in: web, type: task

#29983 Improve `@Lazy`'s javadoc by adding @code tag
  spring-context/src/main/java/org/springframework/context/annotation/Lazy.java
Labels: type: task, in: core

#29116 Protect JMS connection creation against prepareConnection errors
  spring-jms/src/main/java/org/springframework/jms/connection/SingleConnectionFactory.java
  spring-jms/src/test/java/org/springframework/jms/connection/SingleConnectionFactoryTests.java
Labels: in: messaging, type: bug
