Repository spring-projects/spring-framework, pull requests merged in 2023-04, with the labels that each got.

#30238 Rename MockMVC matcher methods to prevent regression in user tests
  spring-test/src/main/java/org/springframework/test/web/client/match/MockRestRequestMatchers.java
  spring-test/src/test/java/org/springframework/test/web/client/match/MockRestRequestMatchersTests.java
Labels: in: test, status: backported, in: web

#30123 Add a couple missing java.time types to StatementCreatorUtils
  spring-jdbc/src/main/java/org/springframework/jdbc/core/StatementCreatorUtils.java
  spring-jdbc/src/test/java/org/springframework/jdbc/core/StatementCreatorUtilsTests.java
Labels: in: data, type: enhancement

#30166 Replace `Collections.unmodifiableList(new ArrayList(..))` with `List.copyOf()`
  spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/reactive/PayloadMethodArgumentResolver.java
  spring-messaging/src/main/java/org/springframework/messaging/rsocket/DefaultMetadataExtractor.java
  spring-web/src/main/java/org/springframework/http/converter/AbstractHttpMessageConverter.java
  spring-web/src/main/java/org/springframework/web/util/HierarchicalUriComponents.java
Labels: in: web, type: enhancement

#30169 ConstructorResolver error hints about mixing indexed and named args
  spring-beans/src/main/java/org/springframework/beans/factory/support/ConstructorResolver.java
  spring-beans/src/test/java/org/springframework/beans/factory/DefaultListableBeanFactoryTests.java
Labels: in: core, type: enhancement

#30216 Use log4j-slf4j2-impl
  build.gradle
Labels: type: task

#30365 Fix `@link` in Javadoc of `PassThroughFilterChain`
  spring-test/src/main/java/org/springframework/mock/web/PassThroughFilterChain.java
  spring-web/src/testFixtures/java/org/springframework/web/testfixture/servlet/PassThroughFilterChain.java
Labels: in: test, type: documentation, in: web

#30361 Optimize DefaultLifecycleProcessor::stopBeans
  spring-context/src/main/java/org/springframework/context/support/DefaultLifecycleProcessor.java
Labels: in: core, type: enhancement

#30369 Add ReloadableResourceBundleMessageSource Resource selection hook
  spring-context/src/main/java/org/springframework/context/support/ReloadableResourceBundleMessageSource.java
Labels: in: core, type: enhancement
