Repository spring-projects/spring-framework, pull requests merged in 2023-07, with the labels that each got.

#30878 Update to antora-ui-spring v0.3.1
  antora-playbook.yml
  lib/antora/templates/per-branch-antora-playbook.yml
Labels: type: task

#30879 Update to spring-antora-ui v0.3.2
  antora-playbook.yml
  lib/antora/templates/per-branch-antora-playbook.yml
Labels: type: task

#27735 DataAccessUtils result accessors with Optional return value
  spring-tx/src/main/java/org/springframework/dao/support/DataAccessUtils.java
  spring-tx/src/test/java/org/springframework/dao/support/DataAccessUtilsTests.java
Labels: in: data, type: enhancement

#30911 Update to antora-ui-spring 0.3.3
  antora-playbook.yml
  lib/antora/templates/per-branch-antora-playbook.yml
Labels: status: waiting-for-triage
