Repository spring-projects/spring-framework, pull requests merged in 2023-08, with the labels that each got.

#31006 Fix misspelling of `applicationListenerDectector` variable
  spring-context/src/main/java/org/springframework/context/support/ApplicationListenerDetector.java
Labels: type: task, in: core

#31022 Docs build updates
  .github/workflows/deploy-docs.yml
  antora-playbook.yml
  build.gradle
Labels: type: documentation

#31084 Add `@Nullable` to `value` in `param()` methods in `JdbcClient`
  spring-jdbc/src/main/java/org/springframework/jdbc/core/simple/DefaultJdbcClient.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/simple/JdbcClient.java
Labels: in: data, type: enhancement

#31126 Update to antora-ui-spring 0.3.5
  antora-playbook.yml
  lib/antora/templates/per-branch-antora-playbook.yml
Labels: type: task
