Repository spring-projects/spring-framework, pull requests merged in 2023-01, with the labels that each got.

#29748 Fix wrong asserted code in SQLExceptionSubclassTranslatorTests
  spring-jdbc/src/test/java/org/springframework/jdbc/support/SQLExceptionSubclassTranslatorTests.java
Labels: type: enhancement

#29727 Add Kotlin DSL support for MockMVC andExpectAll
  spring-test/src/main/kotlin/org/springframework/test/web/servlet/MockMvcResultMatchersDsl.kt
  spring-test/src/main/kotlin/org/springframework/test/web/servlet/ResultActionsDsl.kt
  spring-test/src/test/kotlin/org/springframework/test/web/servlet/MockMvcExtensionsTests.kt
Labels: in: test, type: enhancement, in: kotlin

#29816 Deprecate HttpStatus 103 CHECKPOINT in favor of new EARLY_HINTS
  spring-test/src/main/java/org/springframework/test/web/servlet/result/StatusResultMatchers.java
  spring-test/src/main/kotlin/org/springframework/test/web/servlet/result/StatusResultMatchersDsl.kt
  spring-web/src/main/java/org/springframework/http/HttpStatus.java
  spring-web/src/main/java/org/springframework/http/HttpStatusCode.java
  spring-web/src/test/java/org/springframework/http/HttpStatusTests.java
Labels: in: web, type: enhancement

#29800 Fix R2dbcTransactionManager debug log: don't log a Mono
  spring-r2dbc/src/main/java/org/springframework/r2dbc/connection/R2dbcTransactionManager.java
Labels: in: data, status: backported, type: enhancement

#29854 Remove extra empty line in reactive `DefaultCorsProcessor`
  spring-web/src/main/java/org/springframework/web/cors/reactive/DefaultCorsProcessor.java
Labels: type: task
