Repository spring-projects/spring-framework, pull requests merged in 2023-05, with the labels that each got.

#30415 Add Antora docs-build branch
  .github/workflows/deploy-docs.yml
  .sdkmanrc
  README.adoc
  antora-playbook.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/antora/templates/per-branch-antora-playbook.yml
Labels: type: documentation

#30425 nohttp exclude **/.gradle/**
  buildSrc/src/main/java/org/springframework/build/CheckstyleConventions.java
Labels: type: task

#30424 rwinch to spring-projects
  antora-playbook.yml
Labels: type: task

#30352 Clarify behavior of the Elvis SpEL operator in documentation
  framework-docs/modules/ROOT/pages/core/expressions/language-ref/operator-elvis.adoc
  spring-expression/src/main/java/org/springframework/expression/spel/ast/Elvis.java
Labels: type: documentation, in: core

#30045 Add SpEL support for registered MethodHandles
  framework-docs/modules/ROOT/pages/core/expressions.adoc
  framework-docs/modules/ROOT/pages/core/expressions/language-ref.adoc
  framework-docs/modules/ROOT/pages/core/expressions/language-ref/functions.adoc
  spring-expression/src/main/java/org/springframework/expression/spel/ast/FunctionReference.java
  spring-expression/src/main/java/org/springframework/expression/spel/support/ReflectionHelper.java
  spring-expression/src/main/java/org/springframework/expression/spel/support/StandardEvaluationContext.java
  spring-expression/src/test/java/org/springframework/expression/spel/ExpressionLanguageScenarioTests.java
  spring-expression/src/test/java/org/springframework/expression/spel/SpelDocumentationTests.java
  spring-expression/src/test/java/org/springframework/expression/spel/TestScenarioCreator.java
Labels: in: core, type: enhancement

#30020 Add test support to record async events, with Junit5 caveat
  spring-test/spring-test.gradle
  spring-test/src/main/java/org/springframework/test/context/event/ApplicationEventsHolder.java
  spring-test/src/main/java/org/springframework/test/context/event/DefaultApplicationEvents.java
  spring-test/src/main/java/org/springframework/test/context/junit/jupiter/SpringExtension.java
  spring-test/src/test/java/org/springframework/test/context/junit/jupiter/event/JUnitJupiterApplicationEventsIntegrationTests.java
  spring-test/src/test/java/org/springframework/test/context/junit/jupiter/event/ParallelApplicationEventsIntegrationTests.java
  spring-test/src/test/java/org/springframework/test/context/junit4/event/JUnit4ApplicationEventsAsyncIntegrationTests.java
  spring-test/src/test/java/org/springframework/test/context/testng/event/TestNGApplicationEventsAsyncIntegrationTests.java
Labels: in: test, type: enhancement

#30432 Enable tabs-sync-option for the Antora based reference documentation
  antora-playbook.yml
Labels: type: task

#30530 Port BeanPropertyRowMapper and DataClassRowMapper for r2dbc
  spring-r2dbc/src/main/java/org/springframework/r2dbc/core/BeanPropertyRowMapper.java
  spring-r2dbc/src/main/java/org/springframework/r2dbc/core/DataClassRowMapper.java
  spring-r2dbc/src/test/java/org/springframework/r2dbc/core/BeanPropertyRowMapperTests.java
  spring-r2dbc/src/test/java/org/springframework/r2dbc/core/DataClassRowMapperTests.java
Labels: in: data, type: enhancement

#30546 Support parsing `long` dates in `InstantFormatter`
  spring-context/src/main/java/org/springframework/format/datetime/standard/InstantFormatter.java
  spring-context/src/test/java/org/springframework/format/datetime/standard/DateTimeFormattingTests.java
  spring-context/src/test/java/org/springframework/format/datetime/standard/InstantFormatterTests.java
Labels: in: core, type: enhancement
