Repository spring-projects/spring-framework, pull requests merged in 2024-01, with the labels that each got.

#31939 Update autowired-qualifiers.adoc to refer the -parameters Java compiler flag
  framework-docs/modules/ROOT/pages/core/beans/annotation-config/autowired-qualifiers.adoc
Labels: type: documentation, in: core

#31966 Update SDKMAN config to use 17.0.9-librca
  .sdkmanrc
Labels: type: task

#32056 Update to antora-extensions 1.8.2
  build.gradle
Labels: type: documentation

#32066 Update to spring-io/spring-doc-actions v0.0.14
  .github/workflows/deploy-docs.yml
Labels: type: documentation

#32083 Fixes atlas-extension order
  antora-playbook.yml
Labels: type: documentation
