Repository spring-projects/spring-framework, pull requests merged in 2024-05, with the labels that each got.

#32653 Adds support for qualifying columns with table.
  spring-jdbc/src/main/java/org/springframework/jdbc/support/rowset/ResultSetWrappingSqlRowSet.java
Labels: in: data, type: enhancement

#32782 Polishing
  spring-jdbc/src/main/java/org/springframework/jdbc/support/rowset/ResultSetWrappingSqlRowSet.java
Labels: in: data, type: task

#32784 Insist on using `CollectionUtils.isEmpty()` and `StringUtils.hasLength()`
  spring-core/src/main/java/org/springframework/util/MultiValueMapAdapter.java
  spring-test/src/test/java/org/springframework/test/web/servlet/samples/client/standalone/MultipartControllerTests.java
  spring-test/src/test/java/org/springframework/test/web/servlet/samples/standalone/MultipartControllerTests.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/support/AbstractFlashMapManager.java
Labels: in: web, type: task, in: core

#32829 Improve wording in Spring Framework Overview documentation
  framework-docs/modules/ROOT/pages/overview.adoc
Labels: type: documentation

#32893 Add update-antora-ui-spring.yml workflow
  .github/workflows/update-antora-ui-spring.yml
Labels: type: documentation
