Repository spring-projects/spring-framework, pull requests merged in 2024-02, with the labels that each got.

#32118 Refactor ReloadableResourceBundleMessageSource
  spring-context/src/main/java/org/springframework/context/support/ReloadableResourceBundleMessageSource.java
Labels: in: core, type: enhancement

#32216 Variables definition fixed
  framework-docs/modules/ROOT/pages/testing/spring-mvc-test-framework/server-setup-options.adoc
Labels: type: documentation

#32218 Fix typo in beanvalidation.adoc
  framework-docs/modules/ROOT/pages/core/validation/beanvalidation.adoc
Labels: type: documentation

#32265 Fix Kotlin syntax errors in RestClient builder example in rest-clients.adoc
  framework-docs/modules/ROOT/pages/integration/rest-clients.adoc
Labels: type: documentation, in: web

#30079 Resolve type variable recursively in `GenericTypeResolver`
  spring-context/src/main/java/org/springframework/context/event/ApplicationListenerMethodAdapter.java
  spring-core/src/main/java/org/springframework/core/GenericTypeResolver.java
  spring-core/src/main/java/org/springframework/core/ResolvableType.java
  spring-core/src/test/java/org/springframework/core/GenericTypeResolverTests.java
  spring-core/src/test/java/org/springframework/core/ResolvableTypeTests.java
Labels: in: core, type: enhancement

#32308 Replace redundant javadoc with {@inheritDoc} for AbstractBeanDefinition
  spring-beans/src/main/java/org/springframework/beans/factory/config/BeanDefinition.java
  spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanDefinition.java
Labels: type: task, in: core

#32313 Polishing Javadoc
  spring-jdbc/src/main/java/org/springframework/jdbc/IncorrectResultSetColumnCountException.java
  spring-jdbc/src/main/java/org/springframework/jdbc/JdbcUpdateAffectedIncorrectNumberOfRowsException.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/InterruptibleBatchPreparedStatementSetter.java
  spring-jdbc/src/main/java/org/springframework/jdbc/object/RdbmsOperation.java
  spring-jdbc/src/main/java/org/springframework/jdbc/object/StoredProcedure.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/CustomSQLExceptionTranslatorRegistry.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/JdbcUtils.java
  spring-jdbc/src/main/java/org/springframework/jdbc/support/SQLErrorCodesFactory.java
Labels: type: task

#32316 Polishing Javadoc
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/ParameterizableViewController.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/resource/EncodedResourceResolver.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/resource/ResourceHttpRequestHandler.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/resource/ResourceUrlProvider.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/AbstractUrlBasedView.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/JstlView.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/view/RedirectView.java
Labels: in: web, type: task

#32347 Add test for @Fallback with BeanFactory.getBean(Class)
  spring-context/src/test/java/org/springframework/context/annotation/configuration/BeanMethodQualificationTests.java
Labels: type: task, in: core

#32348 Add missing method BeanDefinitionBuilder.setFallback()
  spring-beans/src/main/java/org/springframework/beans/factory/support/BeanDefinitionBuilder.java
  spring-beans/src/test/java/org/springframework/beans/factory/support/BeanDefinitionBuilderTests.java
Labels: type: task, in: core
