Repository spring-projects/spring-framework, pull requests merged in 2024-09, with the labels that each got.

#33452 Expand acronyms `FQN` and `FQCN`
  spring-beans/src/main/java/org/springframework/beans/factory/support/ConstructorResolver.java
  spring-beans/src/main/resources/org/springframework/beans/factory/xml/spring-beans.dtd
  spring-beans/src/main/resources/org/springframework/beans/factory/xml/spring-beans.xsd
  spring-core/src/main/java/org/springframework/aot/hint/RuntimeHintsRegistrar.java
  spring-tx/src/main/java/org/springframework/transaction/interceptor/MethodMapTransactionAttributeSource.java
  spring-tx/src/main/java/org/springframework/transaction/interceptor/TransactionAttributeSourceEditor.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/RuleBasedTransactionAttributeTests.java
  spring-tx/src/test/java/org/springframework/transaction/interceptor/TransactionAttributeSourceEditorTests.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/handler/SimpleMappingExceptionResolver.java
Labels: type: documentation

#33533 `AnnotatedBeanDefinitionReader` should respect `@Fallback` qualifier analogous to `@Primary`
  spring-context/src/main/java/org/springframework/context/annotation/AnnotatedBeanDefinitionReader.java
  spring-context/src/test/java/org/springframework/context/annotation/AnnotatedBeanDefinitionReaderTests.java
Labels: type: bug, in: core

#33597 Polish
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/AbstractMessageConverterMethodArgumentResolver.java
  spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestResponseBodyMethodProcessor.java
Labels: in: web, type: task

#33470 Implemented to throw a runtime error if a class with a method with a @TransactionalEventListener has @Transactional and the propagation level is not REQUIRES_NEW and NOT_SUPPORTED
  spring-tx/src/main/java/org/springframework/transaction/annotation/RestrictedTransactionalEventListenerFactory.java
  spring-tx/src/test/java/org/springframework/transaction/event/TransactionalApplicationListenerMethodAdapterTests.java
Labels: in: data, type: enhancement
