Repository spring-projects/spring-framework, pull requests merged in 2024-03, with the labels that each got.

#32367 enh: use isEmpty() instead of length()
  spring-context/src/main/java/org/springframework/validation/AbstractErrors.java
Labels: in: core, type: enhancement

#32407 Fix typo in documentation: mvc-ann-rest-exceptions.adoc
  framework-docs/modules/ROOT/pages/web/webmvc/mvc-ann-rest-exceptions.adoc
Labels: in: web, type: task

#32413 Polishing Optional usage
  spring-context/src/test/java/org/springframework/context/annotation/configuration/AutowiredConfigurationTests.java
  spring-core/src/testFixtures/java/org/springframework/core/testfixture/TestGroupsCondition.java
  spring-test/src/main/java/org/springframework/test/context/junit/jupiter/AbstractExpressionEvaluatingCondition.java
  spring-web/src/main/java/org/springframework/http/codec/multipart/MultipartHttpMessageWriter.java
Labels: type: task

#32532 Prevent package summaries from being truncated due to incorrect sentence detection
  spring-core/src/main/java/org/springframework/core/type/filter/package-info.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/package-info.java
  spring-webflux/src/main/java/org/springframework/web/reactive/result/view/script/package-info.java
Labels: type: task
