Repository spring-projects/spring-framework, pull requests merged in 2025-03, with the labels that each got.

#34449 Add tests to ensure bean definition flag "fallback" take precedence over "defaultCandidate"
  spring-beans/src/test/java/org/springframework/beans/factory/DefaultListableBeanFactoryTests.java
Labels: type: task, in: core

#34603 Fix formatting and update links to scripting libraries
  framework-docs/modules/ROOT/pages/web/webflux-view.adoc
  framework-docs/modules/ROOT/pages/web/webflux/controller/ann-validation.adoc
  framework-docs/modules/ROOT/pages/web/webmvc-view/mvc-script.adoc
  framework-docs/modules/ROOT/pages/web/webmvc/mvc-controller/ann-validation.adoc
  framework-docs/modules/ROOT/pages/web/webmvc/mvc-security.adoc
Labels: type: documentation

#34668 Stop calling deprecated JdbcOperations methods
  spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
  spring-jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementCallback.java
  spring-jdbc/src/main/kotlin/org/springframework/jdbc/core/JdbcOperationsExtensions.kt
  spring-jdbc/src/test/kotlin/org/springframework/jdbc/core/JdbcOperationsExtensionsTests.kt
Labels: in: data, type: task
