Repository spring-projects/spring-framework, pull requests merged in 2025-07, with the labels that each got.

#35140 Fix potentially loses precision and jitter is not well capped with unit tests
  spring-aop/src/main/java/org/springframework/aop/retry/AbstractRetryInterceptor.java
  spring-aop/src/test/java/org/springframework/aop/retry/ReactiveRetryInterceptorTests.java
Labels: in: core, type: enhancement

#35163 Fix copy-n-paste errors in `JmsClient` Javadoc
  spring-jms/src/main/java/org/springframework/jms/core/JmsClient.java
Labels: in: messaging, type: task

#34696 Improve BeanFactoryExtensionsTests
  spring-beans/src/test/kotlin/org/springframework/beans/factory/BeanFactoryExtensionsTests.kt
Labels: type: task, in: core

#35262 Remove typo in RestTestClient Javadoc
  spring-test/src/main/java/org/springframework/test/web/servlet/client/RestTestClient.java
Labels: in: web, type: task
